// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AclGroupUserSet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AclGroupUserSetGroupSet;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AclGroupUserSetAclGroupUserSetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AclGroupUserSetAclGroupUserSetRoot : GPBRootObject
@end

#pragma mark - AclGroupUserSetGroupSet

typedef GPB_ENUM(AclGroupUserSetGroupSet_FieldNumber) {
  AclGroupUserSetGroupSet_FieldNumber_GroupId = 1,
  AclGroupUserSetGroupSet_FieldNumber_Action = 2,
};

@interface AclGroupUserSetGroupSet : GPBMessage

@property(nonatomic, readwrite) uint64_t groupId;

/** 1: 加入群组; 2: 取消加入群组 */
@property(nonatomic, readwrite) uint32_t action;

@end

#pragma mark - AclGroupUserSetRpcRequest

typedef GPB_ENUM(AclGroupUserSetRpcRequest_FieldNumber) {
  AclGroupUserSetRpcRequest_FieldNumber_AccessToken = 1,
  AclGroupUserSetRpcRequest_FieldNumber_UserId = 10,
  AclGroupUserSetRpcRequest_FieldNumber_GroupArray = 11,
};

/**
 * 请求方填写
 **/
@interface AclGroupUserSetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 设置某一个用户属于一个或者几个群组 */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AclGroupUserSetGroupSet*> *groupArray;
/** The number of items in @c groupArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupArray_Count;

@end

#pragma mark - AclGroupUserSetRpcResponse

/**
 * 返回方填写
 **/
@interface AclGroupUserSetRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
