// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AclGroupList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AclGroupListGroup;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AclGroupListAclGroupListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AclGroupListAclGroupListRoot : GPBRootObject
@end

#pragma mark - AclGroupListGroup

typedef GPB_ENUM(AclGroupListGroup_FieldNumber) {
  AclGroupListGroup_FieldNumber_GroupId = 11,
  AclGroupListGroup_FieldNumber_GroupName = 12,
  AclGroupListGroup_FieldNumber_Enable = 13,
};

@interface AclGroupListGroup : GPBMessage

/** 编辑条件 */
@property(nonatomic, readwrite) uint64_t groupId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@property(nonatomic, readwrite) uint32_t enable;

@end

#pragma mark - AclGroupListRpcRequest

typedef GPB_ENUM(AclGroupListRpcRequest_FieldNumber) {
  AclGroupListRpcRequest_FieldNumber_AccessToken = 1,
  AclGroupListRpcRequest_FieldNumber_Page = 11,
  AclGroupListRpcRequest_FieldNumber_PageSize = 12,
};

/**
 * 请求方填写
 **/
@interface AclGroupListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

@end

#pragma mark - AclGroupListRpcResponse

typedef GPB_ENUM(AclGroupListRpcResponse_FieldNumber) {
  AclGroupListRpcResponse_FieldNumber_Total = 1,
  AclGroupListRpcResponse_FieldNumber_GroupsArray = 2,
};

/**
 * 返回方填写
 **/
@interface AclGroupListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint64_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AclGroupListGroup*> *groupsArray;
/** The number of items in @c groupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
