// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppVerEdit.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AppVerEditAppVerEditRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AppVerEditAppVerEditRoot : GPBRootObject
@end

#pragma mark - AppVerEditRpcRequest

typedef GPB_ENUM(AppVerEditRpcRequest_FieldNumber) {
  AppVerEditRpcRequest_FieldNumber_AccessToken = 1,
  AppVerEditRpcRequest_FieldNumber_AppName = 7,
  AppVerEditRpcRequest_FieldNumber_Ver = 8,
  AppVerEditRpcRequest_FieldNumber_ChangeLog = 9,
  AppVerEditRpcRequest_FieldNumber_Md5 = 10,
  AppVerEditRpcRequest_FieldNumber_URL = 11,
  AppVerEditRpcRequest_FieldNumber_FileId = 12,
};

/**
 * 请求方填写
 **/
@interface AppVerEditRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 修改的检索条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ver;

/** 可修改的内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *changeLog;

@property(nonatomic, readwrite, copy, null_resettable) NSString *md5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@end

#pragma mark - AppVerEditRpcResponse

/**
 * 返回方填写
 **/
@interface AppVerEditRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
