// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompanyList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CompanyListCompanyInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CompanyListCompanyListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CompanyListCompanyListRoot : GPBRootObject
@end

#pragma mark - CompanyListCompanyInfo

typedef GPB_ENUM(CompanyListCompanyInfo_FieldNumber) {
  CompanyListCompanyInfo_FieldNumber_Name = 1,
  CompanyListCompanyInfo_FieldNumber_CompanyCode = 2,
  CompanyListCompanyInfo_FieldNumber_Addr = 3,
  CompanyListCompanyInfo_FieldNumber_AgencyCode = 4,
  CompanyListCompanyInfo_FieldNumber_FileIds = 5,
};

@interface CompanyListCompanyInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *addr;

/** true; 机构代码证 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *agencyCode;

/** true; 文件ID集合 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileIds;

@end

#pragma mark - CompanyListRpcRequest

typedef GPB_ENUM(CompanyListRpcRequest_FieldNumber) {
  CompanyListRpcRequest_FieldNumber_AccessToken = 1,
  CompanyListRpcRequest_FieldNumber_Page = 11,
  CompanyListRpcRequest_FieldNumber_PageSize = 12,
  CompanyListRpcRequest_FieldNumber_CompanyCode = 21,
  CompanyListRpcRequest_FieldNumber_Name = 22,
};

/**
 * 请求方填写
 **/
@interface CompanyListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件; 只返回没有删除，并且经过审核的符合条件的记录 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - CompanyListRpcResponse

typedef GPB_ENUM(CompanyListRpcResponse_FieldNumber) {
  CompanyListRpcResponse_FieldNumber_Total = 11,
  CompanyListRpcResponse_FieldNumber_CompanysArray = 12,
};

/**
 * 返回方填写
 **/
@interface CompanyListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CompanyListCompanyInfo*> *companysArray;
/** The number of items in @c companysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger companysArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
