// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompanyEdit.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CompanyEditCompanyEditRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CompanyEditCompanyEditRoot : GPBRootObject
@end

#pragma mark - CompanyEditRpcRequest

typedef GPB_ENUM(CompanyEditRpcRequest_FieldNumber) {
  CompanyEditRpcRequest_FieldNumber_AccessToken = 1,
  CompanyEditRpcRequest_FieldNumber_CompanyCode = 11,
  CompanyEditRpcRequest_FieldNumber_Addr = 21,
  CompanyEditRpcRequest_FieldNumber_Name = 22,
  CompanyEditRpcRequest_FieldNumber_AgencyCode = 23,
  CompanyEditRpcRequest_FieldNumber_FileIds = 24,
};

/**
 * 请求方填写
 **/
@interface CompanyEditRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** true; 公司唯一代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

/** false; 公司地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *addr;

/** false; 公司名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** true; 机构代码证 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *agencyCode;

/** true; 文件ID集合 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileIds;

@end

#pragma mark - CompanyEditRpcResponse

typedef GPB_ENUM(CompanyEditRpcResponse_FieldNumber) {
  CompanyEditRpcResponse_FieldNumber_CompanyCode = 11,
};

/**
 * 返回方填写
 **/
@interface CompanyEditRpcResponse : GPBMessage

/** true; 公司编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
