// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceEventGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceEventGetEvent;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceEventGetDeviceEventGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceEventGetDeviceEventGetRoot : GPBRootObject
@end

#pragma mark - DeviceEventGetEvent

typedef GPB_ENUM(DeviceEventGetEvent_FieldNumber) {
  DeviceEventGetEvent_FieldNumber_EventId = 1,
  DeviceEventGetEvent_FieldNumber_TimeStamp = 2,
  DeviceEventGetEvent_FieldNumber_Chno = 8,
  DeviceEventGetEvent_FieldNumber_RichType = 9,
  DeviceEventGetEvent_FieldNumber_RichURL = 10,
  DeviceEventGetEvent_FieldNumber_StartTime = 11,
  DeviceEventGetEvent_FieldNumber_TimeLen = 12,
  DeviceEventGetEvent_FieldNumber_SaveSite = 13,
};

@interface DeviceEventGetEvent : GPBMessage

@property(nonatomic, readwrite) int32_t eventId;

@property(nonatomic, readwrite) int64_t timeStamp;

/**
 * 高级参数(主要针对IPC使用)
 * 报警通道
 **/
@property(nonatomic, readwrite) int32_t chno;

/** 0: 没有富媒体;1: JPG; 2: PNG; 11: MP4; 12: AVI; 21: 云存储 */
@property(nonatomic, readwrite) int32_t richType;

/** rich_type = 1,2,11,12 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *richURL;

/** rich_type = 21； 开始时间 */
@property(nonatomic, readwrite) int64_t startTime;

/** 云录像时间长度 */
@property(nonatomic, readwrite) int64_t timeLen;

/** 云存储存放区域: 1, 阿里云中国; 2, 阿里云迪拜; 3..... */
@property(nonatomic, readwrite) int32_t saveSite;

@end

#pragma mark - DeviceEventGetRpcRequest

typedef GPB_ENUM(DeviceEventGetRpcRequest_FieldNumber) {
  DeviceEventGetRpcRequest_FieldNumber_AccessToken = 1,
  DeviceEventGetRpcRequest_FieldNumber_Page = 11,
  DeviceEventGetRpcRequest_FieldNumber_PageSize = 12,
  DeviceEventGetRpcRequest_FieldNumber_DeviceId = 21,
  DeviceEventGetRpcRequest_FieldNumber_SubDeviceId = 22,
};

/**
 * 请求方填写
 **/
@interface DeviceEventGetRpcRequest : GPBMessage

/** true; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件 (默认时间倒序) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@end

#pragma mark - DeviceEventGetRpcResponse

typedef GPB_ENUM(DeviceEventGetRpcResponse_FieldNumber) {
  DeviceEventGetRpcResponse_FieldNumber_Total = 1,
  DeviceEventGetRpcResponse_FieldNumber_DeviceId = 2,
  DeviceEventGetRpcResponse_FieldNumber_SubDeviceId = 3,
  DeviceEventGetRpcResponse_FieldNumber_EventsArray = 5,
};

/**
 * 返回方填写
 **/
@interface DeviceEventGetRpcResponse : GPBMessage

@property(nonatomic, readwrite) int64_t total;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceEventGetEvent*> *eventsArray;
/** The number of items in @c eventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
