// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceDnsQuery.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceDnsQueryDnsInfo;
@class DeviceDnsQueryHostInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceDnsQueryDeviceDnsQueryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceDnsQueryDeviceDnsQueryRoot : GPBRootObject
@end

#pragma mark - DeviceDnsQueryHostInfo

typedef GPB_ENUM(DeviceDnsQueryHostInfo_FieldNumber) {
  DeviceDnsQueryHostInfo_FieldNumber_Ipaddr = 1,
  DeviceDnsQueryHostInfo_FieldNumber_PortArray = 2,
};

@interface DeviceDnsQueryHostInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ipaddr;

/** 可能在一个服务上运行多个端口 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *portArray;
/** The number of items in @c portArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger portArray_Count;

@end

#pragma mark - DeviceDnsQueryDnsInfo

typedef GPB_ENUM(DeviceDnsQueryDnsInfo_FieldNumber) {
  DeviceDnsQueryDnsInfo_FieldNumber_Qtype = 1,
  DeviceDnsQueryDnsInfo_FieldNumber_HostsArray = 2,
};

@interface DeviceDnsQueryDnsInfo : GPBMessage

@property(nonatomic, readwrite) int32_t qtype;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceDnsQueryHostInfo*> *hostsArray;
/** The number of items in @c hostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger hostsArray_Count;

@end

#pragma mark - DeviceDnsQueryRpcRequest

typedef GPB_ENUM(DeviceDnsQueryRpcRequest_FieldNumber) {
  DeviceDnsQueryRpcRequest_FieldNumber_DeviceId = 1,
  DeviceDnsQueryRpcRequest_FieldNumber_DeviceSeckey = 2,
  DeviceDnsQueryRpcRequest_FieldNumber_ClientIpaddr = 10,
  DeviceDnsQueryRpcRequest_FieldNumber_ReqTimestamp = 11,
  DeviceDnsQueryRpcRequest_FieldNumber_QtypeArray = 12,
};

@interface DeviceDnsQueryRpcRequest : GPBMessage

/** true; device_id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

/** true; 设备校验码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

/** 客户端的外网IP地址(可以为空,由apigw获取后填写) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientIpaddr;

/** 请求时设备端的时间戳，单位MS */
@property(nonatomic, readwrite) int64_t reqTimestamp;

/** 需要查询的服务类别 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *qtypeArray;
/** The number of items in @c qtypeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger qtypeArray_Count;

@end

#pragma mark - DeviceDnsQueryRpcResponse

typedef GPB_ENUM(DeviceDnsQueryRpcResponse_FieldNumber) {
  DeviceDnsQueryRpcResponse_FieldNumber_WanIp = 1,
  DeviceDnsQueryRpcResponse_FieldNumber_WanPort = 2,
  DeviceDnsQueryRpcResponse_FieldNumber_ReqTimestamp = 11,
  DeviceDnsQueryRpcResponse_FieldNumber_SrvTimestamp = 12,
  DeviceDnsQueryRpcResponse_FieldNumber_AnsHostsArray = 13,
  DeviceDnsQueryRpcResponse_FieldNumber_IotDnsArray = 14,
};

/**
 * 返回方填写
 **/
@interface DeviceDnsQueryRpcResponse : GPBMessage

/** 连接的外网IP地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *wanIp;

/** 外网端口 */
@property(nonatomic, readwrite) int32_t wanPort;

/** 将请求的时间戳返回 */
@property(nonatomic, readwrite) int64_t reqTimestamp;

/** (同时提供了授时功能)服务器的时间戳(ms)，客户端时间等于: (当前接收到命令的时间-req_timesstamp)/2 + srv_timestamp */
@property(nonatomic, readwrite) int64_t srvTimestamp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceDnsQueryDnsInfo*> *ansHostsArray;
/** The number of items in @c ansHostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ansHostsArray_Count;

/** 可用的iot_dns的地址信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceDnsQueryHostInfo*> *iotDnsArray;
/** The number of items in @c iotDnsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger iotDnsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
