// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceRomList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceRomListRomInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceRomListDeviceRomListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceRomListDeviceRomListRoot : GPBRootObject
@end

#pragma mark - DeviceRomListRomInfo

typedef GPB_ENUM(DeviceRomListRomInfo_FieldNumber) {
  DeviceRomListRomInfo_FieldNumber_ProductCode = 11,
  DeviceRomListRomInfo_FieldNumber_RomVer = 12,
  DeviceRomListRomInfo_FieldNumber_RomMd5 = 13,
  DeviceRomListRomInfo_FieldNumber_FileId = 14,
  DeviceRomListRomInfo_FieldNumber_ChangeLog = 15,
};

@interface DeviceRomListRomInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *changeLog;

@end

#pragma mark - DeviceRomListRpcRequest

typedef GPB_ENUM(DeviceRomListRpcRequest_FieldNumber) {
  DeviceRomListRpcRequest_FieldNumber_AccessToken = 1,
  DeviceRomListRpcRequest_FieldNumber_Page = 11,
  DeviceRomListRpcRequest_FieldNumber_PageSize = 12,
  DeviceRomListRpcRequest_FieldNumber_ProductCode = 21,
  DeviceRomListRpcRequest_FieldNumber_RomVer = 22,
};

/**
 * 请求方填写
 **/
@interface DeviceRomListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件, 只返回Product_code最后的固件版本. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

/** 可选条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

@end

#pragma mark - DeviceRomListRpcResponse

typedef GPB_ENUM(DeviceRomListRpcResponse_FieldNumber) {
  DeviceRomListRpcResponse_FieldNumber_Total = 11,
  DeviceRomListRpcResponse_FieldNumber_RomsArray = 12,
};

/**
 * 返回方填写
 **/
@interface DeviceRomListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceRomListRomInfo*> *romsArray;
/** The number of items in @c romsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger romsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
