// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceRomGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceRomGetDeviceRomGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceRomGetDeviceRomGetRoot : GPBRootObject
@end

#pragma mark - DeviceRomGetRpcRequest

typedef GPB_ENUM(DeviceRomGetRpcRequest_FieldNumber) {
  DeviceRomGetRpcRequest_FieldNumber_DeviceId = 1,
  DeviceRomGetRpcRequest_FieldNumber_DeviceSeckey = 2,
  DeviceRomGetRpcRequest_FieldNumber_SubDeviceId = 3,
  DeviceRomGetRpcRequest_FieldNumber_RomVer = 12,
};

/**
 * 请求方填写
 **/
@interface DeviceRomGetRpcRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

@end

#pragma mark - DeviceRomGetRpcResponse

typedef GPB_ENUM(DeviceRomGetRpcResponse_FieldNumber) {
  DeviceRomGetRpcResponse_FieldNumber_RomVer = 2,
  DeviceRomGetRpcResponse_FieldNumber_RomMd5 = 3,
  DeviceRomGetRpcResponse_FieldNumber_URL = 4,
};

/**
 * 返回方填写
 **/
@interface DeviceRomGetRpcResponse : GPBMessage

/** 最新版本号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

/** 版本MD5(如果有最新固件) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *romMd5;

/** 固件的URL地址(如果有最新固件) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
