// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceInfoGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceInfoGetDeviceInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceInfoGetDeviceInfoGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceInfoGetDeviceInfoGetRoot : GPBRootObject
@end

#pragma mark - DeviceInfoGetDeviceInfo

typedef GPB_ENUM(DeviceInfoGetDeviceInfo_FieldNumber) {
  DeviceInfoGetDeviceInfo_FieldNumber_DeviceId = 1,
  DeviceInfoGetDeviceInfo_FieldNumber_SubDeviceId = 2,
  DeviceInfoGetDeviceInfo_FieldNumber_SwVer = 3,
  DeviceInfoGetDeviceInfo_FieldNumber_HwVer = 4,
  DeviceInfoGetDeviceInfo_FieldNumber_ProdtCodeArray = 5,
  DeviceInfoGetDeviceInfo_FieldNumber_NbiCodeArray = 6,
  DeviceInfoGetDeviceInfo_FieldNumber_ProductCode = 7,
  DeviceInfoGetDeviceInfo_FieldNumber_ProductName = 8,
  DeviceInfoGetDeviceInfo_FieldNumber_CompanyCode = 9,
  DeviceInfoGetDeviceInfo_FieldNumber_Conf = 10,
  DeviceInfoGetDeviceInfo_FieldNumber_Pic1Fileid = 12,
  DeviceInfoGetDeviceInfo_FieldNumber_Pic2Fileid = 13,
  DeviceInfoGetDeviceInfo_FieldNumber_Pic3Fileid = 14,
};

@interface DeviceInfoGetDeviceInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *swVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwVer;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *prodtCodeArray;
/** The number of items in @c prodtCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger prodtCodeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *nbiCodeArray;
/** The number of items in @c nbiCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nbiCodeArray_Count;

/** device_id 才有下面属性 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

/**
 * 设备配置信息,每个 prodt_code对应的的配置信息参见: `device_confi.md`
 * add: 2018-0327 wbw
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conf;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic1Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic2Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic3Fileid;

@end

#pragma mark - DeviceInfoGetRpcRequest

typedef GPB_ENUM(DeviceInfoGetRpcRequest_FieldNumber) {
  DeviceInfoGetRpcRequest_FieldNumber_AccessToken = 1,
  DeviceInfoGetRpcRequest_FieldNumber_DeviceIdArray = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceInfoGetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *deviceIdArray;
/** The number of items in @c deviceIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger deviceIdArray_Count;

@end

#pragma mark - DeviceInfoGetRpcResponse

typedef GPB_ENUM(DeviceInfoGetRpcResponse_FieldNumber) {
  DeviceInfoGetRpcResponse_FieldNumber_VersArray = 11,
};

/**
 * 返回方填写
 **/
@interface DeviceInfoGetRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceInfoGetDeviceInfo*> *versArray;
/** The number of items in @c versArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger versArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
