// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceCmdAdd.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceCmdAddReportCmd;
@class iot_commSIOTCMD;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceCmdAddDeviceCmdAddRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceCmdAddDeviceCmdAddRoot : GPBRootObject
@end

#pragma mark - DeviceCmdAddReportCmd

typedef GPB_ENUM(DeviceCmdAddReportCmd_FieldNumber) {
  DeviceCmdAddReportCmd_FieldNumber_CmdSrc = 1,
  DeviceCmdAddReportCmd_FieldNumber_Cmd = 2,
  DeviceCmdAddReportCmd_FieldNumber_TimeStamp = 3,
  DeviceCmdAddReportCmd_FieldNumber_MsgId = 4,
};

@interface DeviceCmdAddReportCmd : GPBMessage

/** 1：app产生命令 2：联动规则触发命令 3: 场景产生 4: 用户手动触发 */
@property(nonatomic, readwrite) int32_t cmdSrc;

/** 执行的时候事件戳，单位MS */
@property(nonatomic, readwrite) int64_t timeStamp;

@property(nonatomic, readwrite, strong, null_resettable) iot_commSIOTCMD *cmd;
/** Test to see if @c cmd has been set. */
@property(nonatomic, readwrite) BOOL hasCmd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@end

#pragma mark - DeviceCmdAddRpcRequest

typedef GPB_ENUM(DeviceCmdAddRpcRequest_FieldNumber) {
  DeviceCmdAddRpcRequest_FieldNumber_DeviceId = 1,
  DeviceCmdAddRpcRequest_FieldNumber_DeviceSeckey = 2,
  DeviceCmdAddRpcRequest_FieldNumber_SubDeviceId = 3,
  DeviceCmdAddRpcRequest_FieldNumber_RepCmdsArray = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceCmdAddRpcRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceCmdAddReportCmd*> *repCmdsArray;
/** The number of items in @c repCmdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger repCmdsArray_Count;

@end

#pragma mark - DeviceCmdAddRpcResponse

/**
 * 返回方填写
 **/
@interface DeviceCmdAddRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
