// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceAdd.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceAddDeviceAddRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceAddDeviceAddRoot : GPBRootObject
@end

#pragma mark - DeviceAddRpcRequest

typedef GPB_ENUM(DeviceAddRpcRequest_FieldNumber) {
  DeviceAddRpcRequest_FieldNumber_ClientId = 1,
  DeviceAddRpcRequest_FieldNumber_ReqTime = 2,
  DeviceAddRpcRequest_FieldNumber_SignKey = 3,
  DeviceAddRpcRequest_FieldNumber_ProductCode = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceAddRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

/** true;单位秒,请求时间戳，在该时间开始的15分钟内该请求有效，放置数据重放攻击. */
@property(nonatomic, readwrite) int64_t reqTime;

/** true;签名字串,计算方法： md5(req_time + client_srcret) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signKey;

/** true; 产品编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@end

#pragma mark - DeviceAddRpcResponse

typedef GPB_ENUM(DeviceAddRpcResponse_FieldNumber) {
  DeviceAddRpcResponse_FieldNumber_DeviceId = 11,
  DeviceAddRpcResponse_FieldNumber_DeviceSeckey = 12,
};

/**
 * 返回方填写
 **/
@interface DeviceAddRpcResponse : GPBMessage

/** true; 设备ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
