// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceHubDeviceList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceHubDeviceListSubDeviceInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceHubDeviceListDeviceHubDeviceListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceHubDeviceListDeviceHubDeviceListRoot : GPBRootObject
@end

#pragma mark - DeviceHubDeviceListSubDeviceInfo

typedef GPB_ENUM(DeviceHubDeviceListSubDeviceInfo_FieldNumber) {
  DeviceHubDeviceListSubDeviceInfo_FieldNumber_SubDeviceId = 1,
  DeviceHubDeviceListSubDeviceInfo_FieldNumber_DeviceName = 2,
  DeviceHubDeviceListSubDeviceInfo_FieldNumber_ProductId = 3,
  DeviceHubDeviceListSubDeviceInfo_FieldNumber_CreateTime = 4,
};

@interface DeviceHubDeviceListSubDeviceInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;

@property(nonatomic, readwrite) uint32_t createTime;

@end

#pragma mark - DeviceHubDeviceListRpcRequest

typedef GPB_ENUM(DeviceHubDeviceListRpcRequest_FieldNumber) {
  DeviceHubDeviceListRpcRequest_FieldNumber_AccessToken = 1,
  DeviceHubDeviceListRpcRequest_FieldNumber_DeviceId = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceHubDeviceListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@end

#pragma mark - DeviceHubDeviceListRpcResponse

typedef GPB_ENUM(DeviceHubDeviceListRpcResponse_FieldNumber) {
  DeviceHubDeviceListRpcResponse_FieldNumber_SubDevsArray = 11,
};

/**
 * 返回方填写
 **/
@interface DeviceHubDeviceListRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceHubDeviceListSubDeviceInfo*> *subDevsArray;
/** The number of items in @c subDevsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger subDevsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
