// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceRomAdd.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceRomAddDeviceRomAddRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceRomAddDeviceRomAddRoot : GPBRootObject
@end

#pragma mark - DeviceRomAddRpcRequest

typedef GPB_ENUM(DeviceRomAddRpcRequest_FieldNumber) {
  DeviceRomAddRpcRequest_FieldNumber_AccessToken = 1,
  DeviceRomAddRpcRequest_FieldNumber_ProductCode = 11,
  DeviceRomAddRpcRequest_FieldNumber_RomVer = 12,
  DeviceRomAddRpcRequest_FieldNumber_RomMd5 = 13,
  DeviceRomAddRpcRequest_FieldNumber_FileId = 14,
  DeviceRomAddRpcRequest_FieldNumber_ChangeLog = 15,
};

/**
 * 请求方填写
 **/
@interface DeviceRomAddRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *changeLog;

@end

#pragma mark - DeviceRomAddRpcResponse

/**
 * 返回方填写
 **/
@interface DeviceRomAddRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
