// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceFailcodeGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceFailcodeGetFailcodeInfo;
@class DeviceFailcodeGetQueryInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceFailcodeGetDeviceFailcodeGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceFailcodeGetDeviceFailcodeGetRoot : GPBRootObject
@end

#pragma mark - DeviceFailcodeGetQueryInfo

typedef GPB_ENUM(DeviceFailcodeGetQueryInfo_FieldNumber) {
  DeviceFailcodeGetQueryInfo_FieldNumber_DeviceId = 1,
  DeviceFailcodeGetQueryInfo_FieldNumber_SubDeviceId = 2,
};

@interface DeviceFailcodeGetQueryInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@end

#pragma mark - DeviceFailcodeGetFailcodeInfo

typedef GPB_ENUM(DeviceFailcodeGetFailcodeInfo_FieldNumber) {
  DeviceFailcodeGetFailcodeInfo_FieldNumber_DeviceId = 1,
  DeviceFailcodeGetFailcodeInfo_FieldNumber_SubDeviceId = 2,
  DeviceFailcodeGetFailcodeInfo_FieldNumber_FailCode = 3,
  DeviceFailcodeGetFailcodeInfo_FieldNumber_TimeStamp = 4,
};

@interface DeviceFailcodeGetFailcodeInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite) uint32_t failCode;

@property(nonatomic, readwrite) uint32_t timeStamp;

@end

#pragma mark - DeviceFailcodeGetRpcRequest

typedef GPB_ENUM(DeviceFailcodeGetRpcRequest_FieldNumber) {
  DeviceFailcodeGetRpcRequest_FieldNumber_AccessToken = 1,
  DeviceFailcodeGetRpcRequest_FieldNumber_QueryArray = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceFailcodeGetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceFailcodeGetQueryInfo*> *queryArray;
/** The number of items in @c queryArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger queryArray_Count;

@end

#pragma mark - DeviceFailcodeGetRpcResponse

typedef GPB_ENUM(DeviceFailcodeGetRpcResponse_FieldNumber) {
  DeviceFailcodeGetRpcResponse_FieldNumber_FailcodesArray = 11,
};

/**
 * 返回方填写
 **/
@interface DeviceFailcodeGetRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceFailcodeGetFailcodeInfo*> *failcodesArray;
/** The number of items in @c failcodesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger failcodesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
