// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceEventSet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceEventSetDeviceEventSetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceEventSetDeviceEventSetRoot : GPBRootObject
@end

#pragma mark - DeviceEventSetRpcRequest

typedef GPB_ENUM(DeviceEventSetRpcRequest_FieldNumber) {
  DeviceEventSetRpcRequest_FieldNumber_DeviceId = 1,
  DeviceEventSetRpcRequest_FieldNumber_DeviceSeckey = 2,
  DeviceEventSetRpcRequest_FieldNumber_SubDeviceId = 6,
  DeviceEventSetRpcRequest_FieldNumber_EventId = 7,
  DeviceEventSetRpcRequest_FieldNumber_Chno = 8,
  DeviceEventSetRpcRequest_FieldNumber_RichType = 9,
  DeviceEventSetRpcRequest_FieldNumber_RichURL = 10,
  DeviceEventSetRpcRequest_FieldNumber_StartTime = 11,
  DeviceEventSetRpcRequest_FieldNumber_TimeLen = 12,
  DeviceEventSetRpcRequest_FieldNumber_SaveSite = 13,
};

/**
 * 请求方填写
 **/
@interface DeviceEventSetRpcRequest : GPBMessage

/** true; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite) int32_t eventId;

/**
 * 高级参数(主要针对IPC使用)
 * 报警通道
 **/
@property(nonatomic, readwrite) int32_t chno;

/** 0: 没有富媒体;1: JPG; 2: PNG; 11: MP4; 12: AVI; 21: 云存储 */
@property(nonatomic, readwrite) int32_t richType;

/** rich_type = 1,2,11,12 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *richURL;

/** rich_type = 21； 开始时间 */
@property(nonatomic, readwrite) int64_t startTime;

/** 云录像时间长度 */
@property(nonatomic, readwrite) int64_t timeLen;

/** 云存储存放区域: 1, 阿里云中国; 2, 阿里云迪拜; 3..... */
@property(nonatomic, readwrite) int32_t saveSite;

@end

#pragma mark - DeviceEventSetRpcResponse

/**
 * 返回方填写
 **/
@interface DeviceEventSetRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
