// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceStatusGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceStatusGetQueryInfo;
@class DeviceStatusGetStatusInfo;
@class DeviceStatusGetYCMD;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceStatusGetDeviceStatusGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceStatusGetDeviceStatusGetRoot : GPBRootObject
@end

#pragma mark - DeviceStatusGetYCMD

typedef GPB_ENUM(DeviceStatusGetYCMD_FieldNumber) {
  DeviceStatusGetYCMD_FieldNumber_Cmdid = 11,
  DeviceStatusGetYCMD_FieldNumber_ArgInt32Array = 12,
  DeviceStatusGetYCMD_FieldNumber_ArgStringArray = 13,
  DeviceStatusGetYCMD_FieldNumber_ArgBytes = 14,
};

@interface DeviceStatusGetYCMD : GPBMessage

/** 0 忽略后面参数 */
@property(nonatomic, readwrite) int32_t cmdid;

/** 如果有float 扩大相应精度，转化为INT */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *argInt32Array;
/** The number of items in @c argInt32Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argInt32Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *argStringArray;
/** The number of items in @c argStringArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argStringArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *argBytes;

@end

#pragma mark - DeviceStatusGetQueryInfo

typedef GPB_ENUM(DeviceStatusGetQueryInfo_FieldNumber) {
  DeviceStatusGetQueryInfo_FieldNumber_DeviceId = 1,
  DeviceStatusGetQueryInfo_FieldNumber_SubDeviceId = 2,
};

@interface DeviceStatusGetQueryInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@end

#pragma mark - DeviceStatusGetStatusInfo

typedef GPB_ENUM(DeviceStatusGetStatusInfo_FieldNumber) {
  DeviceStatusGetStatusInfo_FieldNumber_SubDeviceId = 1,
  DeviceStatusGetStatusInfo_FieldNumber_Online = 2,
  DeviceStatusGetStatusInfo_FieldNumber_TimeStamp = 3,
  DeviceStatusGetStatusInfo_FieldNumber_LastCmdArray = 7,
  DeviceStatusGetStatusInfo_FieldNumber_DeviceId = 8,
};

@interface DeviceStatusGetStatusInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

/** 1: offline ; 2: online */
@property(nonatomic, readwrite) uint32_t online;

@property(nonatomic, readwrite) int64_t timeStamp;

/** 当前最新的状态信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceStatusGetYCMD*> *lastCmdArray;
/** The number of items in @c lastCmdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger lastCmdArray_Count;

@end

#pragma mark - DeviceStatusGetRpcRequest

typedef GPB_ENUM(DeviceStatusGetRpcRequest_FieldNumber) {
  DeviceStatusGetRpcRequest_FieldNumber_AccessToken = 1,
  DeviceStatusGetRpcRequest_FieldNumber_DevsArray = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceStatusGetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceStatusGetQueryInfo*> *devsArray;
/** The number of items in @c devsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger devsArray_Count;

@end

#pragma mark - DeviceStatusGetRpcResponse

typedef GPB_ENUM(DeviceStatusGetRpcResponse_FieldNumber) {
  DeviceStatusGetRpcResponse_FieldNumber_StatusArray = 11,
};

/**
 * 返回方填写
 **/
@interface DeviceStatusGetRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceStatusGetStatusInfo*> *statusArray;
/** The number of items in @c statusArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger statusArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
