// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceStatusSet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeviceStatusSetStatusInfo;
@class DeviceStatusSetYCMD;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DeviceStatusSetDeviceStatusSetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DeviceStatusSetDeviceStatusSetRoot : GPBRootObject
@end

#pragma mark - DeviceStatusSetYCMD

typedef GPB_ENUM(DeviceStatusSetYCMD_FieldNumber) {
  DeviceStatusSetYCMD_FieldNumber_Cmdid = 11,
  DeviceStatusSetYCMD_FieldNumber_ArgInt32Array = 12,
  DeviceStatusSetYCMD_FieldNumber_ArgStringArray = 13,
  DeviceStatusSetYCMD_FieldNumber_ArgBytes = 14,
};

@interface DeviceStatusSetYCMD : GPBMessage

/** 0 忽略后面参数 */
@property(nonatomic, readwrite) int32_t cmdid;

/** 如果有float 扩大相应精度，转化为INT */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *argInt32Array;
/** The number of items in @c argInt32Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argInt32Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *argStringArray;
/** The number of items in @c argStringArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argStringArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *argBytes;

@end

#pragma mark - DeviceStatusSetStatusInfo

typedef GPB_ENUM(DeviceStatusSetStatusInfo_FieldNumber) {
  DeviceStatusSetStatusInfo_FieldNumber_SubDeviceId = 1,
  DeviceStatusSetStatusInfo_FieldNumber_Online = 2,
  DeviceStatusSetStatusInfo_FieldNumber_TimeStamp = 3,
  DeviceStatusSetStatusInfo_FieldNumber_LastCmdArray = 7,
  DeviceStatusSetStatusInfo_FieldNumber_LastTime = 8,
};

@interface DeviceStatusSetStatusInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

/** 1: offline ; 2: online  0: 不更新该数据 */
@property(nonatomic, readwrite) uint32_t online;

@property(nonatomic, readwrite) int64_t timeStamp;

/** 当前最新的状态信息 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceStatusSetYCMD*> *lastCmdArray;
/** The number of items in @c lastCmdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger lastCmdArray_Count;

@property(nonatomic, readwrite) int64_t lastTime;

@end

#pragma mark - DeviceStatusSetRpcRequest

typedef GPB_ENUM(DeviceStatusSetRpcRequest_FieldNumber) {
  DeviceStatusSetRpcRequest_FieldNumber_DeviceId = 1,
  DeviceStatusSetRpcRequest_FieldNumber_DeviceSeckey = 2,
  DeviceStatusSetRpcRequest_FieldNumber_StatusArray = 11,
};

/**
 * 请求方填写
 **/
@interface DeviceStatusSetRpcRequest : GPBMessage

/** true; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DeviceStatusSetStatusInfo*> *statusArray;
/** The number of items in @c statusArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger statusArray_Count;

@end

#pragma mark - DeviceStatusSetRpcResponse

/**
 * 返回方填写
 **/
@interface DeviceStatusSetRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
