// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventRuleSet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EventRuleSetEventRuleSetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EventRuleSetEventRuleSetRoot : GPBRootObject
@end

#pragma mark - EventRuleSetRpcRequest

typedef GPB_ENUM(EventRuleSetRpcRequest_FieldNumber) {
  EventRuleSetRpcRequest_FieldNumber_AccessToken = 1,
  EventRuleSetRpcRequest_FieldNumber_EtId = 11,
  EventRuleSetRpcRequest_FieldNumber_SetType = 21,
  EventRuleSetRpcRequest_FieldNumber_SetValue = 22,
};

/**
 * 请求方填写
 **/
@interface EventRuleSetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *etId;

/** set_type = 1; 设置 set_value 为 enable 的值; set_type = 2; 设置 set_value 为 prio 的值. */
@property(nonatomic, readwrite) int32_t setType;

@property(nonatomic, readwrite) int32_t setValue;

@end

#pragma mark - EventRuleSetRpcResponse

/**
 * 返回方填写
 **/
@interface EventRuleSetRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
