// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventRuleList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class iot_commRuleInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EventRuleListEventRuleListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EventRuleListEventRuleListRoot : GPBRootObject
@end

#pragma mark - EventRuleListRpcRequest

typedef GPB_ENUM(EventRuleListRpcRequest_FieldNumber) {
  EventRuleListRpcRequest_FieldNumber_AccessToken = 1,
  EventRuleListRpcRequest_FieldNumber_Page = 11,
  EventRuleListRpcRequest_FieldNumber_PageSize = 12,
  EventRuleListRpcRequest_FieldNumber_HouseGuid = 23,
};

/**
 * 请求方填写
 **/
@interface EventRuleListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/**
 * 检索条件
 * string et_id = 21;
 * int32 et_type = 22;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

#pragma mark - EventRuleListRpcResponse

typedef GPB_ENUM(EventRuleListRpcResponse_FieldNumber) {
  EventRuleListRpcResponse_FieldNumber_Total = 1,
  EventRuleListRpcResponse_FieldNumber_RulesArray = 11,
};

/**
 * 返回方填写
 **/
@interface EventRuleListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<iot_commRuleInfo*> *rulesArray;
/** The number of items in @c rulesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rulesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
