// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventRulePullComp.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EventRulePullCompEventRulePullCompRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EventRulePullCompEventRulePullCompRoot : GPBRootObject
@end

#pragma mark - EventRulePullCompRpcRequest

typedef GPB_ENUM(EventRulePullCompRpcRequest_FieldNumber) {
  EventRulePullCompRpcRequest_FieldNumber_DeviceId = 1,
  EventRulePullCompRpcRequest_FieldNumber_DeviceSeckey = 2,
  EventRulePullCompRpcRequest_FieldNumber_EtIdArray = 11,
};

/**
 * 请求方填写
 **/
@interface EventRulePullCompRpcRequest : GPBMessage

/** true; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *etIdArray;
/** The number of items in @c etIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger etIdArray_Count;

@end

#pragma mark - EventRulePullCompRpcResponse

/**
 * 返回方填写
 **/
@interface EventRulePullCompRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
