// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetLog.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GetLogLog;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GetLogGetLogRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetLogGetLogRoot : GPBRootObject
@end

#pragma mark - GetLogLog

typedef GPB_ENUM(GetLogLog_FieldNumber) {
  GetLogLog_FieldNumber_Level = 1,
  GetLogLog_FieldNumber_UserId = 2,
  GetLogLog_FieldNumber_DeviceId = 3,
  GetLogLog_FieldNumber_Log = 4,
  GetLogLog_FieldNumber_CreateTime = 5,
};

@interface GetLogLog : GPBMessage

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *log;

@property(nonatomic, readwrite) uint32_t createTime;

@end

#pragma mark - GetLogRpcRequest

typedef GPB_ENUM(GetLogRpcRequest_FieldNumber) {
  GetLogRpcRequest_FieldNumber_AccessToken = 1,
  GetLogRpcRequest_FieldNumber_Page = 5,
  GetLogRpcRequest_FieldNumber_PageSize = 6,
  GetLogRpcRequest_FieldNumber_DeviceId = 10,
  GetLogRpcRequest_FieldNumber_UserId = 11,
  GetLogRpcRequest_FieldNumber_StartTime = 12,
};

/**
 * 请求方填写
 **/
@interface GetLogRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索信息 (device_id == "" && sub_device_id =="" 表示获取系统消息) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite) uint32_t userId;

/** 该时间点开始的日志 */
@property(nonatomic, readwrite) uint32_t startTime;

@end

#pragma mark - GetLogRpcResponse

typedef GPB_ENUM(GetLogRpcResponse_FieldNumber) {
  GetLogRpcResponse_FieldNumber_Total = 1,
  GetLogRpcResponse_FieldNumber_LogsArray = 2,
};

/**
 * 返回方填写
 **/
@interface GetLogRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GetLogLog*> *logsArray;
/** The number of items in @c logsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger logsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
