// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GetMsgMsgInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GetMsgGetMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface GetMsgGetMsgRoot : GPBRootObject
@end

#pragma mark - GetMsgMsgInfo

typedef GPB_ENUM(GetMsgMsgInfo_FieldNumber) {
  GetMsgMsgInfo_FieldNumber_DeviceId = 5,
  GetMsgMsgInfo_FieldNumber_DeviceName = 6,
  GetMsgMsgInfo_FieldNumber_SubDeviceId = 7,
  GetMsgMsgInfo_FieldNumber_EventId = 8,
  GetMsgMsgInfo_FieldNumber_Chno = 9,
  GetMsgMsgInfo_FieldNumber_RichType = 10,
  GetMsgMsgInfo_FieldNumber_RichURL = 11,
  GetMsgMsgInfo_FieldNumber_StartTime = 12,
  GetMsgMsgInfo_FieldNumber_TimeLen = 13,
  GetMsgMsgInfo_FieldNumber_SaveSite = 14,
  GetMsgMsgInfo_FieldNumber_MsgTitle = 15,
  GetMsgMsgInfo_FieldNumber_MsgBody = 16,
  GetMsgMsgInfo_FieldNumber_CreateTime = 17,
  GetMsgMsgInfo_FieldNumber_Isread = 18,
  GetMsgMsgInfo_FieldNumber_Id_p = 19,
};

@interface GetMsgMsgInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

/** 对应了报警等级,具体参见:`event_id.md` */
@property(nonatomic, readwrite) int32_t eventId;

/**
 * 高级参数(主要针对IPC使用)
 * 报警通道
 **/
@property(nonatomic, readwrite) int32_t chno;

/** 0: 没有富媒体;1: JPG; 2: PNG; 11: MP4; 12: AVI; 21: 云存储 */
@property(nonatomic, readwrite) int32_t richType;

/** rich_type = 1,2,11,12 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *richURL;

/** rich_type = 21； 开始时间,单位秒 */
@property(nonatomic, readwrite) int64_t startTime;

/** 云录像时间长度 */
@property(nonatomic, readwrite) int64_t timeLen;

/** 云存储存放区域: 1, 阿里云中国; 2, 阿里云迪拜; 3..... */
@property(nonatomic, readwrite) int32_t saveSite;

/** 消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgTitle;

/** JSON数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;

/** 消息创建时间 */
@property(nonatomic, readwrite) int64_t createTime;

/** 是否已读 */
@property(nonatomic, readwrite) int32_t isread;

@property(nonatomic, readwrite) int32_t id_p;

@end

#pragma mark - GetMsgRpcRequest

typedef GPB_ENUM(GetMsgRpcRequest_FieldNumber) {
  GetMsgRpcRequest_FieldNumber_AccessToken = 1,
  GetMsgRpcRequest_FieldNumber_Page = 5,
  GetMsgRpcRequest_FieldNumber_PageSize = 6,
  GetMsgRpcRequest_FieldNumber_DeviceId = 10,
  GetMsgRpcRequest_FieldNumber_SubDeviceId = 11,
};

/**
 * 请求方填写
 **/
@interface GetMsgRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索信息 (device_id == "" && sub_device_id =="" 表示获取系统消息) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@end

#pragma mark - GetMsgRpcResponse

typedef GPB_ENUM(GetMsgRpcResponse_FieldNumber) {
  GetMsgRpcResponse_FieldNumber_Total = 1,
  GetMsgRpcResponse_FieldNumber_MsgsArray = 2,
};

/**
 * 返回方填写
 **/
@interface GetMsgRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GetMsgMsgInfo*> *msgsArray;
/** The number of items in @c msgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
