// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: H2MListDevice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class H2MListDeviceDeviceInfo;
@class iot_commIOTCMD;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - H2MListDeviceH2MlistDeviceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface H2MListDeviceH2MlistDeviceRoot : GPBRootObject
@end

#pragma mark - H2MListDeviceDeviceInfo

typedef GPB_ENUM(H2MListDeviceDeviceInfo_FieldNumber) {
  H2MListDeviceDeviceInfo_FieldNumber_SubDeviceId = 1,
  H2MListDeviceDeviceInfo_FieldNumber_Status = 2,
  H2MListDeviceDeviceInfo_FieldNumber_OnlineStatus = 3,
};

@interface H2MListDeviceDeviceInfo : GPBMessage

/** 设备ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

/** 设备最新状态 */
@property(nonatomic, readwrite, strong, null_resettable) iot_commIOTCMD *status;
/** Test to see if @c status has been set. */
@property(nonatomic, readwrite) BOOL hasStatus;

/** 1 离线; 2 在线 */
@property(nonatomic, readwrite) uint32_t onlineStatus;

@end

#pragma mark - H2MListDeviceRpcRequest

typedef GPB_ENUM(H2MListDeviceRpcRequest_FieldNumber) {
  H2MListDeviceRpcRequest_FieldNumber_SubDeviceId = 5,
};

/**
 * 请求方填写
 **/
@interface H2MListDeviceRpcRequest : GPBMessage

/** 需要查询的设备;或者为空获得所有设备. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@end

#pragma mark - H2MListDeviceRpcResponse

typedef GPB_ENUM(H2MListDeviceRpcResponse_FieldNumber) {
  H2MListDeviceRpcResponse_FieldNumber_DevicesArray = 1,
};

/**
 * 返回方填写
 **/
@interface H2MListDeviceRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<H2MListDeviceDeviceInfo*> *devicesArray;
/** The number of items in @c devicesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger devicesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
