// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HouseEdit.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HouseEditHouseEditRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HouseEditHouseEditRoot : GPBRootObject
@end

#pragma mark - HouseEditRpcRequest

typedef GPB_ENUM(HouseEditRpcRequest_FieldNumber) {
  HouseEditRpcRequest_FieldNumber_AccessToken = 1,
  HouseEditRpcRequest_FieldNumber_HouseGuid = 10,
  HouseEditRpcRequest_FieldNumber_HouseName = 11,
  HouseEditRpcRequest_FieldNumber_AddrName = 12,
  HouseEditRpcRequest_FieldNumber_Longitude = 13,
  HouseEditRpcRequest_FieldNumber_Latitude = 14,
};

/**
 * 请求方填写
 **/
@interface HouseEditRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 编辑条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

/** 编辑内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *addrName;

@property(nonatomic, readwrite) int32_t longitude;

@property(nonatomic, readwrite) int32_t latitude;

@end

#pragma mark - HouseEditRpcResponse

typedef GPB_ENUM(HouseEditRpcResponse_FieldNumber) {
  HouseEditRpcResponse_FieldNumber_HouseGuid = 6,
};

/**
 * 返回方填写
 **/
@interface HouseEditRpcResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
