// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HouseAreaList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HouseAreaListAreaInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HouseAreaListHouseAreaListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HouseAreaListHouseAreaListRoot : GPBRootObject
@end

#pragma mark - HouseAreaListAreaInfo

typedef GPB_ENUM(HouseAreaListAreaInfo_FieldNumber) {
  HouseAreaListAreaInfo_FieldNumber_HouseGuid = 1,
  HouseAreaListAreaInfo_FieldNumber_AreaGuid = 2,
  HouseAreaListAreaInfo_FieldNumber_AreaName = 3,
  HouseAreaListAreaInfo_FieldNumber_IsDefault = 4,
  HouseAreaListAreaInfo_FieldNumber_ResId = 10,
};

@interface HouseAreaListAreaInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *areaGuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *areaName;

/** 1 默认区域，其余为0 */
@property(nonatomic, readwrite) int32_t isDefault;

/** 使用资源编号(用于存放情景图片名称) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resId;

@end

#pragma mark - HouseAreaListRpcRequest

typedef GPB_ENUM(HouseAreaListRpcRequest_FieldNumber) {
  HouseAreaListRpcRequest_FieldNumber_AccessToken = 1,
  HouseAreaListRpcRequest_FieldNumber_HouseGuid = 21,
};

/**
 * 请求方填写
 **/
@interface HouseAreaListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

#pragma mark - HouseAreaListRpcResponse

typedef GPB_ENUM(HouseAreaListRpcResponse_FieldNumber) {
  HouseAreaListRpcResponse_FieldNumber_AreasArray = 11,
};

/**
 * 返回方填写
 **/
@interface HouseAreaListRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HouseAreaListAreaInfo*> *areasArray;
/** The number of items in @c areasArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger areasArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
