// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HouseList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HouseListHouseInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HouseListHouseListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HouseListHouseListRoot : GPBRootObject
@end

#pragma mark - HouseListHouseInfo

typedef GPB_ENUM(HouseListHouseInfo_FieldNumber) {
  HouseListHouseInfo_FieldNumber_HouseGuid = 10,
  HouseListHouseInfo_FieldNumber_HouseName = 11,
  HouseListHouseInfo_FieldNumber_AddrName = 12,
  HouseListHouseInfo_FieldNumber_Longitude = 13,
  HouseListHouseInfo_FieldNumber_Latitude = 14,
  HouseListHouseInfo_FieldNumber_UserId = 15,
  HouseListHouseInfo_FieldNumber_IsConfirm = 16,
  HouseListHouseInfo_FieldNumber_Role = 17,
};

@interface HouseListHouseInfo : GPBMessage

/** 编辑条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

/** 编辑内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *addrName;

@property(nonatomic, readwrite) int32_t longitude;

@property(nonatomic, readwrite) int32_t latitude;

@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) int32_t isConfirm;

@property(nonatomic, readwrite) int32_t role;

@end

#pragma mark - HouseListRpcRequest

typedef GPB_ENUM(HouseListRpcRequest_FieldNumber) {
  HouseListRpcRequest_FieldNumber_AccessToken = 1,
  HouseListRpcRequest_FieldNumber_HouseGuid = 11,
};

/**
 * 请求方填写
 **/
@interface HouseListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 如果为空，返回所有家庭信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

#pragma mark - HouseListRpcResponse

typedef GPB_ENUM(HouseListRpcResponse_FieldNumber) {
  HouseListRpcResponse_FieldNumber_HousesArray = 2,
};

/**
 * 返回方填写
 **/
@interface HouseListRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HouseListHouseInfo*> *housesArray;
/** The number of items in @c housesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger housesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
