// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HouseDefenseGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HouseDefenseGetDefenseInfo;
@class HouseDefenseGetDevice;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HouseDefenseGetHouseDefenseGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HouseDefenseGetHouseDefenseGetRoot : GPBRootObject
@end

#pragma mark - HouseDefenseGetDevice

typedef GPB_ENUM(HouseDefenseGetDevice_FieldNumber) {
  HouseDefenseGetDevice_FieldNumber_DeviceId = 1,
  HouseDefenseGetDevice_FieldNumber_SubDeviceId = 2,
  HouseDefenseGetDevice_FieldNumber_EventId = 3,
};

@interface HouseDefenseGetDevice : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite) uint32_t eventId;

@end

#pragma mark - HouseDefenseGetDefenseInfo

typedef GPB_ENUM(HouseDefenseGetDefenseInfo_FieldNumber) {
  HouseDefenseGetDefenseInfo_FieldNumber_HomeGuid = 1,
  HouseDefenseGetDefenseInfo_FieldNumber_DefenseType = 2,
  HouseDefenseGetDefenseInfo_FieldNumber_DevsArray = 3,
  HouseDefenseGetDefenseInfo_FieldNumber_NotifyArray = 4,
};

@interface HouseDefenseGetDefenseInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *homeGuid;

/** 布防类型: 1 .外出布防；2.在家布防；3.撤防 */
@property(nonatomic, readwrite) uint32_t defenseType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HouseDefenseGetDevice*> *devsArray;
/** The number of items in @c devsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger devsArray_Count;

/** 通知类型数组,可以多种: 1.app; 2.短信；3.电话；4.邮件 */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *notifyArray;
/** The number of items in @c notifyArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notifyArray_Count;

@end

#pragma mark - HouseDefenseGetRpcRequest

typedef GPB_ENUM(HouseDefenseGetRpcRequest_FieldNumber) {
  HouseDefenseGetRpcRequest_FieldNumber_AccessToken = 1,
  HouseDefenseGetRpcRequest_FieldNumber_HomeGuid = 6,
};

/**
 * 请求方填写
 **/
@interface HouseDefenseGetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 检索条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *homeGuid;

@end

#pragma mark - HouseDefenseGetRpcResponse

typedef GPB_ENUM(HouseDefenseGetRpcResponse_FieldNumber) {
  HouseDefenseGetRpcResponse_FieldNumber_DefensesArray = 1,
};

/**
 * 返回方填写
 **/
@interface HouseDefenseGetRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HouseDefenseGetDefenseInfo*> *defensesArray;
/** The number of items in @c defensesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger defensesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
