// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HouseAdd.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HouseAddHouseAddRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HouseAddHouseAddRoot : GPBRootObject
@end

#pragma mark - HouseAddRpcRequest

typedef GPB_ENUM(HouseAddRpcRequest_FieldNumber) {
  HouseAddRpcRequest_FieldNumber_AccessToken = 1,
  HouseAddRpcRequest_FieldNumber_HouseName = 11,
  HouseAddRpcRequest_FieldNumber_AddrName = 12,
  HouseAddRpcRequest_FieldNumber_Longitude = 13,
  HouseAddRpcRequest_FieldNumber_Latitude = 14,
};

/**
 * 请求方填写
 **/
@interface HouseAddRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *addrName;

/** value = 200 表示没有设置经纬度 */
@property(nonatomic, readwrite) int32_t longitude;

/** value = 200 表示没有设置经纬度 */
@property(nonatomic, readwrite) int32_t latitude;

@end

#pragma mark - HouseAddRpcResponse

typedef GPB_ENUM(HouseAddRpcResponse_FieldNumber) {
  HouseAddRpcResponse_FieldNumber_HouseGuid = 6,
};

/**
 * 返回方填写
 **/
@interface HouseAddRpcResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
