// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HouseMemberList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HouseMemberListMemberInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - HouseMemberListHouseMemberListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface HouseMemberListHouseMemberListRoot : GPBRootObject
@end

#pragma mark - HouseMemberListMemberInfo

typedef GPB_ENUM(HouseMemberListMemberInfo_FieldNumber) {
  HouseMemberListMemberInfo_FieldNumber_UserId = 1,
  HouseMemberListMemberInfo_FieldNumber_Role = 2,
  HouseMemberListMemberInfo_FieldNumber_IsConfirm = 3,
};

@interface HouseMemberListMemberInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t userId;

/** 0: 普通用户; 1 创建者; 2 创建者设置的管理者 */
@property(nonatomic, readwrite) int32_t role;

/** 0, 受到邀请，用户没有确认： 1, 用户确认加入;2, 用户拒绝加入 ;10, 主动加入需要管理员确认： 11 ,管理员确认; 12, 管理员拒绝 */
@property(nonatomic, readwrite) int32_t isConfirm;

@end

#pragma mark - HouseMemberListRpcRequest

typedef GPB_ENUM(HouseMemberListRpcRequest_FieldNumber) {
  HouseMemberListRpcRequest_FieldNumber_AccessToken = 1,
  HouseMemberListRpcRequest_FieldNumber_HouseGuid = 11,
};

/**
 * 请求方填写
 **/
@interface HouseMemberListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 如果为空，返回所有家庭信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

#pragma mark - HouseMemberListRpcResponse

typedef GPB_ENUM(HouseMemberListRpcResponse_FieldNumber) {
  HouseMemberListRpcResponse_FieldNumber_UsersArray = 2,
};

/**
 * 返回方填写
 **/
@interface HouseMemberListRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HouseMemberListMemberInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
