// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iot_comm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class iot_commExprInfo;
@class iot_commIOTCMD;
@class iot_commRhsInfo;
@class iot_commSIOTCMD;
@class iot_commYCMD;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - iot_commIotCommRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface iot_commIotCommRoot : GPBRootObject
@end

#pragma mark - iot_commYCMD

typedef GPB_ENUM(iot_commYCMD_FieldNumber) {
  iot_commYCMD_FieldNumber_Cmdid = 11,
  iot_commYCMD_FieldNumber_ArgInt32Array = 12,
  iot_commYCMD_FieldNumber_ArgStringArray = 13,
  iot_commYCMD_FieldNumber_ArgBytes = 14,
};

@interface iot_commYCMD : GPBMessage

@property(nonatomic, readwrite) int32_t cmdid;

/** 如果有float 扩大相应精度，转化为INT */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *argInt32Array;
/** The number of items in @c argInt32Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argInt32Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *argStringArray;
/** The number of items in @c argStringArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argStringArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *argBytes;

@end

#pragma mark - iot_commSIOTCMD

typedef GPB_ENUM(iot_commSIOTCMD_FieldNumber) {
  iot_commSIOTCMD_FieldNumber_CmdType = 1,
  iot_commSIOTCMD_FieldNumber_DeviceId = 5,
  iot_commSIOTCMD_FieldNumber_SubDeviceId = 6,
  iot_commSIOTCMD_FieldNumber_CmdsArray = 7,
};

@interface iot_commSIOTCMD : GPBMessage

/** 1 请求； 2 执行应答; 3 报告状态(D-->S) */
@property(nonatomic, readwrite) int32_t cmdType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<iot_commYCMD*> *cmdsArray;
/** The number of items in @c cmdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cmdsArray_Count;

@end

#pragma mark - iot_commIOTCMD

typedef GPB_ENUM(iot_commIOTCMD_FieldNumber) {
  iot_commIOTCMD_FieldNumber_CmdArray = 1,
};

@interface iot_commIOTCMD : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<iot_commSIOTCMD*> *cmdArray;
/** The number of items in @c cmdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cmdArray_Count;

@end

#pragma mark - iot_commCmdRecord

typedef GPB_ENUM(iot_commCmdRecord_FieldNumber) {
  iot_commCmdRecord_FieldNumber_DeviceId = 1,
  iot_commCmdRecord_FieldNumber_SubDeviceId = 2,
  iot_commCmdRecord_FieldNumber_Cmdid = 3,
  iot_commCmdRecord_FieldNumber_ArgInt32Array = 4,
  iot_commCmdRecord_FieldNumber_ArgStringArray = 5,
  iot_commCmdRecord_FieldNumber_ArgBytes = 6,
  iot_commCmdRecord_FieldNumber_CmdSrc = 7,
  iot_commCmdRecord_FieldNumber_IsRun = 8,
  iot_commCmdRecord_FieldNumber_CreateTime = 9,
  iot_commCmdRecord_FieldNumber_RunTime = 10,
  iot_commCmdRecord_FieldNumber_UserId = 11,
};

@interface iot_commCmdRecord : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite) int32_t cmdid;

/** 如果有float 扩大相应精度，转化为INT */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *argInt32Array;
/** The number of items in @c argInt32Array without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argInt32Array_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *argStringArray;
/** The number of items in @c argStringArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger argStringArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *argBytes;

/** */
@property(nonatomic, readwrite) int32_t cmdSrc;

@property(nonatomic, readwrite) int32_t isRun;

@property(nonatomic, readwrite) int64_t createTime;

@property(nonatomic, readwrite) int64_t runTime;

@property(nonatomic, readwrite) uint32_t userId;

@end

#pragma mark - iot_commExprInfo

typedef GPB_ENUM(iot_commExprInfo_FieldNumber) {
  iot_commExprInfo_FieldNumber_ExprId = 1,
  iot_commExprInfo_FieldNumber_Class_p = 2,
  iot_commExprInfo_FieldNumber_StartTime = 3,
  iot_commExprInfo_FieldNumber_EndTime = 4,
  iot_commExprInfo_FieldNumber_DeviceId = 5,
  iot_commExprInfo_FieldNumber_SubDeviceId = 6,
  iot_commExprInfo_FieldNumber_ItemType = 7,
  iot_commExprInfo_FieldNumber_ItemIndex = 8,
  iot_commExprInfo_FieldNumber_Expr = 9,
  iot_commExprInfo_FieldNumber_Value = 10,
  iot_commExprInfo_FieldNumber_WeekDaysArray = 15,
};

/**
 * ExprInfo 智能联动条件定义
 **/
@interface iot_commExprInfo : GPBMessage

@property(nonatomic, readwrite) int32_t exprId;

/** 1 传感器设备触发; 2 时间要素触发 */
@property(nonatomic, readwrite) int32_t class_p;

/** 2018-03-13 ; 一周当中的星期几: 1-7; */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *weekDaysArray;
/** The number of items in @c weekDaysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger weekDaysArray_Count;

@property(nonatomic, readwrite) int32_t startTime;

@property(nonatomic, readwrite) int32_t endTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

/** 当前只支持 1: int32; 2: string; 3: bytes */
@property(nonatomic, readwrite) int32_t itemType;

/** 从0开始计数 */
@property(nonatomic, readwrite) int32_t itemIndex;

/** < > <= >= == != */
@property(nonatomic, readwrite, copy, null_resettable) NSString *expr;

@property(nonatomic, readwrite) int32_t value;

@end

#pragma mark - iot_commRhsInfo

typedef GPB_ENUM(iot_commRhsInfo_FieldNumber) {
  iot_commRhsInfo_FieldNumber_ActionType = 1,
  iot_commRhsInfo_FieldNumber_SceneId = 11,
  iot_commRhsInfo_FieldNumber_DelaySec = 12,
  iot_commRhsInfo_FieldNumber_Cmd = 13,
};

/**
 * RhsInfo 执行部分动作定义
 **/
@interface iot_commRhsInfo : GPBMessage

/** 1: 控制设备; 2: 控制情景; 3: 控制设备在一定时间范围内； 4： 控制设备延迟多久触发 */
@property(nonatomic, readwrite) int32_t actionType;

/** action_type = 2 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneId;

/** action_type = 3, 4 */
@property(nonatomic, readwrite) int32_t delaySec;

/** action_type = 1,3,4 */
@property(nonatomic, readwrite, strong, null_resettable) iot_commSIOTCMD *cmd;
/** Test to see if @c cmd has been set. */
@property(nonatomic, readwrite) BOOL hasCmd;

@end

#pragma mark - iot_commRuleInfo

typedef GPB_ENUM(iot_commRuleInfo_FieldNumber) {
  iot_commRuleInfo_FieldNumber_EtId = 1,
  iot_commRuleInfo_FieldNumber_DeviceId = 2,
  iot_commRuleInfo_FieldNumber_EtName = 3,
  iot_commRuleInfo_FieldNumber_Prio = 4,
  iot_commRuleInfo_FieldNumber_Enable = 5,
  iot_commRuleInfo_FieldNumber_OnlyTime = 6,
  iot_commRuleInfo_FieldNumber_Lhs = 7,
  iot_commRuleInfo_FieldNumber_ExprsArray = 8,
  iot_commRuleInfo_FieldNumber_RhsArray = 9,
  iot_commRuleInfo_FieldNumber_IsEnd = 10,
  iot_commRuleInfo_FieldNumber_EtType = 11,
  iot_commRuleInfo_FieldNumber_HouseGuid = 12,
  iot_commRuleInfo_FieldNumber_UserId = 13,
};

/**
 * RuleInfo 智能联动规则
 **/
@interface iot_commRuleInfo : GPBMessage

/** 编辑条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *etId;

/** 编辑内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *etName;

/** 触发优先级(数字越小优先级越高),该数字唯一 */
@property(nonatomic, readwrite) int32_t prio;

/** 是否启用: 1: 启用; 2：不启用 */
@property(nonatomic, readwrite) int32_t enable;

/** 条件是否只有时间规则(只有时间规则的用cron调用): 1 是；2 不是 */
@property(nonatomic, readwrite) int32_t onlyTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lhs;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<iot_commExprInfo*> *exprsArray;
/** The number of items in @c exprsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger exprsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<iot_commRhsInfo*> *rhsArray;
/** The number of items in @c rhsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rhsArray_Count;

@property(nonatomic, readwrite) int32_t isEnd;

/** 类型:1, Public 平台定义; 2, User 用户设置; 3, 第三方服务机构设置； 4, 平台自动学习设置 */
@property(nonatomic, readwrite) int32_t etType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@property(nonatomic, readwrite) uint32_t userId;

@end

#pragma mark - iot_commSceneInfo

typedef GPB_ENUM(iot_commSceneInfo_FieldNumber) {
  iot_commSceneInfo_FieldNumber_SceneId = 1,
  iot_commSceneInfo_FieldNumber_SceneType = 3,
  iot_commSceneInfo_FieldNumber_Enable = 4,
  iot_commSceneInfo_FieldNumber_HouseGuid = 5,
  iot_commSceneInfo_FieldNumber_ResId = 10,
  iot_commSceneInfo_FieldNumber_SceneName = 11,
  iot_commSceneInfo_FieldNumber_Cmd = 12,
};

/**
 * SceneInfo 情景信息
 **/
@interface iot_commSceneInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneId;

/** 1, 平台定义的情景; 2, 用户自定义的情景 */
@property(nonatomic, readwrite) int32_t sceneType;

@property(nonatomic, readwrite) int32_t enable;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneName;

@property(nonatomic, readwrite, strong, null_resettable) iot_commIOTCMD *cmd;
/** Test to see if @c cmd has been set. */
@property(nonatomic, readwrite) BOOL hasCmd;

/** 使用资源编号(用于存放情景图片名称) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
