// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IotCmdList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class IotCmdListIotCmd;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - IotCmdListIotCmdListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface IotCmdListIotCmdListRoot : GPBRootObject
@end

#pragma mark - IotCmdListIotCmd

typedef GPB_ENUM(IotCmdListIotCmd_FieldNumber) {
  IotCmdListIotCmd_FieldNumber_Cmdid = 1,
  IotCmdListIotCmd_FieldNumber_CmdType = 2,
  IotCmdListIotCmd_FieldNumber_DetailEn = 3,
  IotCmdListIotCmd_FieldNumber_DetailCn = 4,
  IotCmdListIotCmd_FieldNumber_ArgType = 5,
  IotCmdListIotCmd_FieldNumber_ArgV = 6,
  IotCmdListIotCmd_FieldNumber_ArgDetailEn = 7,
  IotCmdListIotCmd_FieldNumber_ArgDetailCn = 8,
  IotCmdListIotCmd_FieldNumber_ProdtCode = 9,
};

@interface IotCmdListIotCmd : GPBMessage

@property(nonatomic, readwrite) uint32_t cmdid;

@property(nonatomic, readwrite) uint32_t cmdType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailEn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailCn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argV;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argDetailEn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argDetailCn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtCode;

@end

#pragma mark - IotCmdListRpcRequest

typedef GPB_ENUM(IotCmdListRpcRequest_FieldNumber) {
  IotCmdListRpcRequest_FieldNumber_AccessToken = 1,
  IotCmdListRpcRequest_FieldNumber_Page = 5,
  IotCmdListRpcRequest_FieldNumber_PageSize = 6,
  IotCmdListRpcRequest_FieldNumber_Cmdid = 10,
  IotCmdListRpcRequest_FieldNumber_ProdtCode = 11,
};

/**
 * 请求方填写
 **/
@interface IotCmdListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件,只返回经过审核且没有删除的记录 */
@property(nonatomic, readwrite) uint32_t cmdid;

/** 可选 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtCode;

@end

#pragma mark - IotCmdListRpcResponse

typedef GPB_ENUM(IotCmdListRpcResponse_FieldNumber) {
  IotCmdListRpcResponse_FieldNumber_Total = 11,
  IotCmdListRpcResponse_FieldNumber_CmdsArray = 12,
};

/**
 * 返回方填写
 **/
@interface IotCmdListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<IotCmdListIotCmd*> *cmdsArray;
/** The number of items in @c cmdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cmdsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
