// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IotCmdAdd.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - IotCmdAddIotCmdAddRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface IotCmdAddIotCmdAddRoot : GPBRootObject
@end

#pragma mark - IotCmdAddRpcRequest

typedef GPB_ENUM(IotCmdAddRpcRequest_FieldNumber) {
  IotCmdAddRpcRequest_FieldNumber_AccessToken = 1,
  IotCmdAddRpcRequest_FieldNumber_ProdtCode = 10,
  IotCmdAddRpcRequest_FieldNumber_Cmdid = 11,
  IotCmdAddRpcRequest_FieldNumber_CmdType = 12,
  IotCmdAddRpcRequest_FieldNumber_DetailEn = 13,
  IotCmdAddRpcRequest_FieldNumber_DetailCn = 14,
  IotCmdAddRpcRequest_FieldNumber_ArgType = 15,
  IotCmdAddRpcRequest_FieldNumber_ArgV = 16,
  IotCmdAddRpcRequest_FieldNumber_ArgDetailEn = 17,
  IotCmdAddRpcRequest_FieldNumber_ArgDetailCn = 18,
};

/**
 * 请求方填写
 **/
@interface IotCmdAddRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtCode;

@property(nonatomic, readwrite) uint32_t cmdid;

@property(nonatomic, readwrite) uint32_t cmdType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailEn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detailCn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argV;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argDetailEn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argDetailCn;

@end

#pragma mark - IotCmdAddRpcResponse

typedef GPB_ENUM(IotCmdAddRpcResponse_FieldNumber) {
  IotCmdAddRpcResponse_FieldNumber_Cmdid = 11,
};

/**
 * 返回方填写
 **/
@interface IotCmdAddRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t cmdid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
