// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ListObject.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ListObjectFileInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ListObjectListObjectRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ListObjectListObjectRoot : GPBRootObject
@end

#pragma mark - ListObjectFileInfo

typedef GPB_ENUM(ListObjectFileInfo_FieldNumber) {
  ListObjectFileInfo_FieldNumber_LastTime = 9,
  ListObjectFileInfo_FieldNumber_FileId = 10,
  ListObjectFileInfo_FieldNumber_Name = 11,
  ListObjectFileInfo_FieldNumber_TagsArray = 12,
  ListObjectFileInfo_FieldNumber_Md5 = 13,
  ListObjectFileInfo_FieldNumber_Size = 14,
};

@interface ListObjectFileInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

/** 文件名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 该文件的标签 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

/** 文件MD5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *md5;

/** 文件大小 */
@property(nonatomic, readwrite) int32_t size;

/** 文件更改时间(Sec) */
@property(nonatomic, readwrite) int64_t lastTime;

@end

#pragma mark - ListObjectRpcRequest

typedef GPB_ENUM(ListObjectRpcRequest_FieldNumber) {
  ListObjectRpcRequest_FieldNumber_AccessToken = 1,
  ListObjectRpcRequest_FieldNumber_Page = 11,
  ListObjectRpcRequest_FieldNumber_PageSize = 12,
  ListObjectRpcRequest_FieldNumber_StartTime = 13,
};

/**
 * 请求方填写
 **/
@interface ListObjectRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 查询条件? */
@property(nonatomic, readwrite) int64_t startTime;

@end

#pragma mark - ListObjectRpcResponse

typedef GPB_ENUM(ListObjectRpcResponse_FieldNumber) {
  ListObjectRpcResponse_FieldNumber_Totla = 1,
  ListObjectRpcResponse_FieldNumber_FilesArray = 11,
};

/**
 * 返回方填写
 **/
@interface ListObjectRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t totla;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ListObjectFileInfo*> *filesArray;
/** The number of items in @c filesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
