// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: M2HStatusSet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class iot_commIOTCMD;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - M2HStatusSetM2HstatusSetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface M2HStatusSetM2HstatusSetRoot : GPBRootObject
@end

#pragma mark - M2HStatusSetRpcRequest

typedef GPB_ENUM(M2HStatusSetRpcRequest_FieldNumber) {
  M2HStatusSetRpcRequest_FieldNumber_DeviceId = 1,
  M2HStatusSetRpcRequest_FieldNumber_DeviceSeckey = 2,
  M2HStatusSetRpcRequest_FieldNumber_CCmd = 6,
};

/**
 * 请求方填写
 **/
@interface M2HStatusSetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, strong, null_resettable) iot_commIOTCMD *cCmd;
/** Test to see if @c cCmd has been set. */
@property(nonatomic, readwrite) BOOL hasCCmd;

@end

#pragma mark - M2HStatusSetRpcResponse

/**
 * 返回方填写
 **/
@interface M2HStatusSetRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
