// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProdtList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ProdtListProdtInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProdtListProdtListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProdtListProdtListRoot : GPBRootObject
@end

#pragma mark - ProdtListProdtInfo

typedef GPB_ENUM(ProdtListProdtInfo_FieldNumber) {
  ProdtListProdtInfo_FieldNumber_ProdtName = 1,
  ProdtListProdtInfo_FieldNumber_ProdtCode = 2,
};

@interface ProdtListProdtInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtCode;

@end

#pragma mark - ProdtListRpcRequest

typedef GPB_ENUM(ProdtListRpcRequest_FieldNumber) {
  ProdtListRpcRequest_FieldNumber_AccessToken = 1,
  ProdtListRpcRequest_FieldNumber_Page = 5,
  ProdtListRpcRequest_FieldNumber_PageSize = 6,
  ProdtListRpcRequest_FieldNumber_ProdtCode = 10,
};

/**
 * 请求方填写
 **/
@interface ProdtListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/**
 * 只返回没有删除，并且经过审核的记录
 * false; 可以为空
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtCode;

@end

#pragma mark - ProdtListRpcResponse

typedef GPB_ENUM(ProdtListRpcResponse_FieldNumber) {
  ProdtListRpcResponse_FieldNumber_Total = 11,
  ProdtListRpcResponse_FieldNumber_ProdtsArray = 12,
};

/**
 * 返回方填写
 **/
@interface ProdtListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProdtListProdtInfo*> *prodtsArray;
/** The number of items in @c prodtsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger prodtsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
