// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ProductListProductInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProductListProductListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProductListProductListRoot : GPBRootObject
@end

#pragma mark - ProductListProductInfo

typedef GPB_ENUM(ProductListProductInfo_FieldNumber) {
  ProductListProductInfo_FieldNumber_ProductName = 1,
  ProductListProductInfo_FieldNumber_CompanyCode = 2,
  ProductListProductInfo_FieldNumber_Pic1Fileid = 3,
  ProductListProductInfo_FieldNumber_Pic2Fileid = 4,
  ProductListProductInfo_FieldNumber_Remark = 5,
  ProductListProductInfo_FieldNumber_IsReview = 6,
  ProductListProductInfo_FieldNumber_ReviewMark = 7,
  ProductListProductInfo_FieldNumber_NbiCodeArray = 16,
  ProductListProductInfo_FieldNumber_ProdtCodeArray = 17,
};

@interface ProductListProductInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *productName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic1Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic2Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

/** 0, 等待审核；1， 审核通过；2，审核拒绝 */
@property(nonatomic, readwrite) uint32_t isReview;

/** 如果is_review=2 ;该处为拒绝理由 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reviewMark;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *nbiCodeArray;
/** The number of items in @c nbiCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nbiCodeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *prodtCodeArray;
/** The number of items in @c prodtCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger prodtCodeArray_Count;

@end

#pragma mark - ProductListRpcRequest

typedef GPB_ENUM(ProductListRpcRequest_FieldNumber) {
  ProductListRpcRequest_FieldNumber_AccessToken = 1,
  ProductListRpcRequest_FieldNumber_Page = 11,
  ProductListRpcRequest_FieldNumber_PageSize = 12,
  ProductListRpcRequest_FieldNumber_CompanyCode = 21,
  ProductListRpcRequest_FieldNumber_Name = 22,
};

/**
 * 请求方填写
 **/
@interface ProductListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - ProductListRpcResponse

typedef GPB_ENUM(ProductListRpcResponse_FieldNumber) {
  ProductListRpcResponse_FieldNumber_Total = 11,
  ProductListRpcResponse_FieldNumber_ProductsArray = 12,
};

/**
 * 返回方填写
 **/
@interface ProductListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProductListProductInfo*> *productsArray;
/** The number of items in @c productsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger productsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
