// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductCmdList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ProductCmdListCmdList;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProductCmdListProductCmdListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProductCmdListProductCmdListRoot : GPBRootObject
@end

#pragma mark - ProductCmdListCmdList

typedef GPB_ENUM(ProductCmdListCmdList_FieldNumber) {
  ProductCmdListCmdList_FieldNumber_ProductCode = 11,
  ProductCmdListCmdList_FieldNumber_RomVer = 12,
  ProductCmdListCmdList_FieldNumber_Cmdid = 13,
  ProductCmdListCmdList_FieldNumber_CmdType = 14,
  ProductCmdListCmdList_FieldNumber_ArgV = 15,
  ProductCmdListCmdList_FieldNumber_ArgType = 16,
  ProductCmdListCmdList_FieldNumber_ArgDetailEn = 17,
  ProductCmdListCmdList_FieldNumber_ArgDetailCn = 18,
};

@interface ProductCmdListCmdList : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

@property(nonatomic, readwrite) uint32_t cmdid;

@property(nonatomic, readwrite) uint32_t cmdType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argV;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argDetailEn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *argDetailCn;

@end

#pragma mark - ProductCmdListRpcRequest

typedef GPB_ENUM(ProductCmdListRpcRequest_FieldNumber) {
  ProductCmdListRpcRequest_FieldNumber_AccessToken = 1,
  ProductCmdListRpcRequest_FieldNumber_Page = 11,
  ProductCmdListRpcRequest_FieldNumber_PageSize = 12,
  ProductCmdListRpcRequest_FieldNumber_ProductCode = 21,
  ProductCmdListRpcRequest_FieldNumber_RomVer = 22,
};

/**
 * 请求方填写
 **/
@interface ProductCmdListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *romVer;

@end

#pragma mark - ProductCmdListRpcResponse

typedef GPB_ENUM(ProductCmdListRpcResponse_FieldNumber) {
  ProductCmdListRpcResponse_FieldNumber_Total = 11,
  ProductCmdListRpcResponse_FieldNumber_CmdsArray = 12,
};

/**
 * 返回方填写
 **/
@interface ProductCmdListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProductCmdListCmdList*> *cmdsArray;
/** The number of items in @c cmdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cmdsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
