// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RelationList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RelationListRelationInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RelationListRelationListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RelationListRelationListRoot : GPBRootObject
@end

#pragma mark - RelationListRelationInfo

typedef GPB_ENUM(RelationListRelationInfo_FieldNumber) {
  RelationListRelationInfo_FieldNumber_RelationCode = 1,
  RelationListRelationInfo_FieldNumber_RelationDesc = 2,
};

@interface RelationListRelationInfo : GPBMessage

/** true;关系代码 */
@property(nonatomic, readwrite) uint32_t relationCode;

/** true; 关系描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *relationDesc;

@end

#pragma mark - RelationListRpcRequest

typedef GPB_ENUM(RelationListRpcRequest_FieldNumber) {
  RelationListRpcRequest_FieldNumber_AccessToken = 1,
  RelationListRpcRequest_FieldNumber_Page = 11,
  RelationListRpcRequest_FieldNumber_PageSize = 12,
  RelationListRpcRequest_FieldNumber_RelationCode = 21,
};

/**
 * 请求方填写
 **/
@interface RelationListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** 检索条件; 返回未删除的记录 */
@property(nonatomic, readwrite) uint32_t relationCode;

@end

#pragma mark - RelationListRpcResponse

typedef GPB_ENUM(RelationListRpcResponse_FieldNumber) {
  RelationListRpcResponse_FieldNumber_Total = 1,
  RelationListRpcResponse_FieldNumber_RisArray = 11,
};

/**
 * 返回方填写
 **/
@interface RelationListRpcResponse : GPBMessage

/** true; 总共多少条数据 */
@property(nonatomic, readwrite) uint32_t total;

/** true; 返回这次符合条件的数据 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RelationListRelationInfo*> *risArray;
/** The number of items in @c risArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger risArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
