// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SceneList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class iot_commSceneInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SceneListSceneListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SceneListSceneListRoot : GPBRootObject
@end

#pragma mark - SceneListRpcRequest

typedef GPB_ENUM(SceneListRpcRequest_FieldNumber) {
  SceneListRpcRequest_FieldNumber_AccessToken = 1,
  SceneListRpcRequest_FieldNumber_Page = 11,
  SceneListRpcRequest_FieldNumber_PageSize = 12,
  SceneListRpcRequest_FieldNumber_HouseGuid = 21,
};

/**
 * 请求方填写
 **/
@interface SceneListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

#pragma mark - SceneListRpcResponse

typedef GPB_ENUM(SceneListRpcResponse_FieldNumber) {
  SceneListRpcResponse_FieldNumber_Total = 1,
  SceneListRpcResponse_FieldNumber_ScenesArray = 11,
};

/**
 * 返回方填写
 **/
@interface SceneListRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<iot_commSceneInfo*> *scenesArray;
/** The number of items in @c scenesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger scenesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
