// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenePullComp.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ScenePullCompSceneAns;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ScenePullCompScenePullCompRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ScenePullCompScenePullCompRoot : GPBRootObject
@end

#pragma mark - ScenePullCompSceneAns

typedef GPB_ENUM(ScenePullCompSceneAns_FieldNumber) {
  ScenePullCompSceneAns_FieldNumber_HouseGuid = 10,
  ScenePullCompSceneAns_FieldNumber_SceneIdArray = 11,
};

@interface ScenePullCompSceneAns : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *sceneIdArray;
/** The number of items in @c sceneIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sceneIdArray_Count;

@end

#pragma mark - ScenePullCompRpcRequest

typedef GPB_ENUM(ScenePullCompRpcRequest_FieldNumber) {
  ScenePullCompRpcRequest_FieldNumber_DeviceId = 1,
  ScenePullCompRpcRequest_FieldNumber_DeviceSeckey = 2,
  ScenePullCompRpcRequest_FieldNumber_ScenesArray = 11,
};

/**
 * 请求方填写
 **/
@interface ScenePullCompRpcRequest : GPBMessage

/** true; */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceSeckey;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ScenePullCompSceneAns*> *scenesArray;
/** The number of items in @c scenesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger scenesArray_Count;

@end

#pragma mark - ScenePullCompRpcResponse

/**
 * 返回方填写
 **/
@interface ScenePullCompRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
