// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SendMsgSendMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SendMsgSendMsgRoot : GPBRootObject
@end

#pragma mark - SendMsgRpcRequest

typedef GPB_ENUM(SendMsgRpcRequest_FieldNumber) {
  SendMsgRpcRequest_FieldNumber_ClientId = 1,
  SendMsgRpcRequest_FieldNumber_ReqTime = 2,
  SendMsgRpcRequest_FieldNumber_SignKey = 3,
  SendMsgRpcRequest_FieldNumber_UserIdArray = 4,
  SendMsgRpcRequest_FieldNumber_DeviceId = 5,
  SendMsgRpcRequest_FieldNumber_SubDeviceId = 6,
  SendMsgRpcRequest_FieldNumber_EventId = 7,
  SendMsgRpcRequest_FieldNumber_Chno = 8,
  SendMsgRpcRequest_FieldNumber_RichType = 9,
  SendMsgRpcRequest_FieldNumber_RichURL = 10,
  SendMsgRpcRequest_FieldNumber_StartTime = 11,
  SendMsgRpcRequest_FieldNumber_TimeLen = 12,
  SendMsgRpcRequest_FieldNumber_SaveSite = 13,
  SendMsgRpcRequest_FieldNumber_MsgTitle = 14,
  SendMsgRpcRequest_FieldNumber_MsgBody = 15,
};

/**
 * 请求方填写
 **/
@interface SendMsgRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

/** true;单位秒,请求时间戳，在该时间开始的15分钟内该请求有效，放置数据重放攻击. */
@property(nonatomic, readwrite) int64_t reqTime;

/** true;签名字串,计算方法： md5(req_time + client_srcret) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signKey;

/** true;用户ID,与device_id互斥 */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *userIdArray;
/** The number of items in @c userIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

/** 对应了报警等级,具体参见:`event_id.md` */
@property(nonatomic, readwrite) int32_t eventId;

/**
 * 高级参数(主要针对IPC使用)
 * 报警通道
 **/
@property(nonatomic, readwrite) int32_t chno;

/** 0: 没有富媒体;1: JPG; 2: PNG; 11: MP4; 12: AVI; 21: 云存储 */
@property(nonatomic, readwrite) int32_t richType;

/** rich_type = 1,2,11,12 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *richURL;

/** rich_type = 21； 开始时间,单位秒 */
@property(nonatomic, readwrite) int64_t startTime;

/** 云录像时间长度 */
@property(nonatomic, readwrite) int64_t timeLen;

/** 云存储存放区域: 1, 阿里云中国; 2, 阿里云迪拜; 3..... */
@property(nonatomic, readwrite) int32_t saveSite;

/** 消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgTitle;

/** JSON数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;

@end

#pragma mark - SendMsgRpcResponse

/**
 * 返回方填写
 **/
@interface SendMsgRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
