// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SetObjectTags.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SetObjectTagsSetObjectTagsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SetObjectTagsSetObjectTagsRoot : GPBRootObject
@end

#pragma mark - SetObjectTagsRpcRequest

typedef GPB_ENUM(SetObjectTagsRpcRequest_FieldNumber) {
  SetObjectTagsRpcRequest_FieldNumber_AccessToken = 1,
  SetObjectTagsRpcRequest_FieldNumber_FileId = 10,
  SetObjectTagsRpcRequest_FieldNumber_TagsArray = 11,
};

/**
 * 请求方填写
 **/
@interface SetObjectTagsRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** 文件ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

@end

#pragma mark - SetObjectTagsRpcResponse

typedef GPB_ENUM(SetObjectTagsRpcResponse_FieldNumber) {
  SetObjectTagsRpcResponse_FieldNumber_FileId = 10,
};

/**
 * 返回方填写
 **/
@interface SetObjectTagsRpcResponse : GPBMessage

/** 文件ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
