// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPhoneChange.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserPhoneChangeUserPhoneChangeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserPhoneChangeUserPhoneChangeRoot : GPBRootObject
@end

#pragma mark - UserPhoneChangeRpcRequest

typedef GPB_ENUM(UserPhoneChangeRpcRequest_FieldNumber) {
  UserPhoneChangeRpcRequest_FieldNumber_AccessToken = 1,
  UserPhoneChangeRpcRequest_FieldNumber_OldPhone = 11,
  UserPhoneChangeRpcRequest_FieldNumber_OldVcode = 12,
  UserPhoneChangeRpcRequest_FieldNumber_NewPhone = 13,
  UserPhoneChangeRpcRequest_FieldNumber_NewVcode = 14,
};

/**
 * 请求方填写
 **/
@interface UserPhoneChangeRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *oldPhone;

/** 验证码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *oldVcode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *newPhone NS_RETURNS_NOT_RETAINED;

@property(nonatomic, readwrite, copy, null_resettable) NSString *newVcode NS_RETURNS_NOT_RETAINED;

@end

#pragma mark - UserPhoneChangeRpcResponse

/**
 * 返回方填写
 **/
@interface UserPhoneChangeRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
