// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserFRSList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserFRSListFRSInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserFRSListUserFrslistRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserFRSListUserFrslistRoot : GPBRootObject
@end

#pragma mark - UserFRSListFRSInfo

typedef GPB_ENUM(UserFRSListFRSInfo_FieldNumber) {
  UserFRSListFRSInfo_FieldNumber_UserName = 1,
  UserFRSListFRSInfo_FieldNumber_RelationCode = 2,
  UserFRSListFRSInfo_FieldNumber_IsConfirm = 3,
  UserFRSListFRSInfo_FieldNumber_CreateTime = 4,
  UserFRSListFRSInfo_FieldNumber_UserId = 6,
  UserFRSListFRSInfo_FieldNumber_RelationUserId = 7,
  UserFRSListFRSInfo_FieldNumber_Remark = 9,
};

@interface UserFRSListFRSInfo : GPBMessage

/** true;被建立关系的用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

/** true;关系描述 */
@property(nonatomic, readwrite) uint32_t relationCode;

/** true;关系描述是否被系统或者对方确认，0,未确认关系；1，系统正在审核关系；2，已经确认关系成立;3,对方拒绝建立关系 */
@property(nonatomic, readwrite) uint32_t isConfirm;

/** true; 添加关系时间戳，单位秒 */
@property(nonatomic, readwrite) uint32_t createTime;

/** true; 用户ID */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite) uint32_t relationUserId;

/** true; 备注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

@end

#pragma mark - UserFRSListRpcRequest

typedef GPB_ENUM(UserFRSListRpcRequest_FieldNumber) {
  UserFRSListRpcRequest_FieldNumber_AccessToken = 1,
};

/**
 * 请求方填写
 **/
@interface UserFRSListRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@end

#pragma mark - UserFRSListRpcResponse

typedef GPB_ENUM(UserFRSListRpcResponse_FieldNumber) {
  UserFRSListRpcResponse_FieldNumber_FrsArray = 11,
};

/**
 * 返回方填写
 **/
@interface UserFRSListRpcResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserFRSListFRSInfo*> *frsArray;
/** The number of items in @c frsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger frsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
