// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserDnsQuery.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserDnsQueryDnsInfo;
@class UserDnsQueryHostInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserDnsQueryUserDnsQueryRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserDnsQueryUserDnsQueryRoot : GPBRootObject
@end

#pragma mark - UserDnsQueryHostInfo

typedef GPB_ENUM(UserDnsQueryHostInfo_FieldNumber) {
  UserDnsQueryHostInfo_FieldNumber_Ipaddr = 1,
  UserDnsQueryHostInfo_FieldNumber_PortArray = 2,
};

@interface UserDnsQueryHostInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ipaddr;

/** 可能在一个服务上运行多个端口 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *portArray;
/** The number of items in @c portArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger portArray_Count;

@end

#pragma mark - UserDnsQueryDnsInfo

typedef GPB_ENUM(UserDnsQueryDnsInfo_FieldNumber) {
  UserDnsQueryDnsInfo_FieldNumber_Host = 1,
  UserDnsQueryDnsInfo_FieldNumber_HostsArray = 2,
};

@interface UserDnsQueryDnsInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *host;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserDnsQueryHostInfo*> *hostsArray;
/** The number of items in @c hostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger hostsArray_Count;

@end

#pragma mark - UserDnsQueryRpcRequest

typedef GPB_ENUM(UserDnsQueryRpcRequest_FieldNumber) {
  UserDnsQueryRpcRequest_FieldNumber_ClientId = 1,
  UserDnsQueryRpcRequest_FieldNumber_ReqTime = 2,
  UserDnsQueryRpcRequest_FieldNumber_SignKey = 3,
  UserDnsQueryRpcRequest_FieldNumber_ClientIpaddr = 10,
  UserDnsQueryRpcRequest_FieldNumber_ReqTimestamp = 11,
  UserDnsQueryRpcRequest_FieldNumber_HostArray = 12,
  UserDnsQueryRpcRequest_FieldNumber_UserName = 13,
};

@interface UserDnsQueryRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

/** true;单位秒,请求时间戳，在该时间开始的15分钟内该请求有效，放置数据重放攻击. */
@property(nonatomic, readwrite) int64_t reqTime;

/** true;签名字串,计算方法： md5(req_time + client_srcret) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signKey;

/** 客户端的外网IP地址(可以为空,由apigw获取后填写) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientIpaddr;

/** 请求时设备端的时间戳，单位MS */
@property(nonatomic, readwrite) int64_t reqTimestamp;

/** 需要查询的主机名 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *hostArray;
/** The number of items in @c hostArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger hostArray_Count;

/** 2018-0308 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@end

#pragma mark - UserDnsQueryRpcResponse

typedef GPB_ENUM(UserDnsQueryRpcResponse_FieldNumber) {
  UserDnsQueryRpcResponse_FieldNumber_ReqTimestamp = 11,
  UserDnsQueryRpcResponse_FieldNumber_SrvTimestamp = 12,
  UserDnsQueryRpcResponse_FieldNumber_AnsHostsArray = 13,
  UserDnsQueryRpcResponse_FieldNumber_ApiGatewayArray = 14,
};

/**
 * 返回方填写
 **/
@interface UserDnsQueryRpcResponse : GPBMessage

/** 将请求的时间戳返回 */
@property(nonatomic, readwrite) int64_t reqTimestamp;

/** 服务器的时间戳(ms)，客户端时间等于: (当前接收到命令的时间-req_timesstamp)/2 + srv_timestamp */
@property(nonatomic, readwrite) int64_t srvTimestamp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserDnsQueryDnsInfo*> *ansHostsArray;
/** The number of items in @c ansHostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ansHostsArray_Count;

/** 可用的api_gateway地址 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserDnsQueryHostInfo*> *apiGatewayArray;
/** The number of items in @c apiGatewayArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger apiGatewayArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
