// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAttrSet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserAttrSetAttr;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserAttrSetUserAttrSetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserAttrSetUserAttrSetRoot : GPBRootObject
@end

#pragma mark - UserAttrSetAttr

typedef GPB_ENUM(UserAttrSetAttr_FieldNumber) {
  UserAttrSetAttr_FieldNumber_ItemId = 1,
  UserAttrSetAttr_FieldNumber_ItemVstring = 2,
  UserAttrSetAttr_FieldNumber_ItemVint32 = 3,
};

@interface UserAttrSetAttr : GPBMessage

@property(nonatomic, readwrite) int32_t itemId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *itemVstring;

@property(nonatomic, readwrite) int32_t itemVint32;

@end

#pragma mark - UserAttrSetRpcRequest

typedef GPB_ENUM(UserAttrSetRpcRequest_FieldNumber) {
  UserAttrSetRpcRequest_FieldNumber_AccessToken = 1,
  UserAttrSetRpcRequest_FieldNumber_UserId = 11,
  UserAttrSetRpcRequest_FieldNumber_AttrsArray = 12,
};

/**
 * 请求方填写
 **/
@interface UserAttrSetRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** true; 用户名集合 */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserAttrSetAttr*> *attrsArray;
/** The number of items in @c attrsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attrsArray_Count;

@end

#pragma mark - UserAttrSetRpcResponse

/**
 * 返回方填写
 **/
@interface UserAttrSetRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
