// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserFRSConfirm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserFRSConfirmUserFrsconfirmRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserFRSConfirmUserFrsconfirmRoot : GPBRootObject
@end

#pragma mark - UserFRSConfirmRpcRequest

typedef GPB_ENUM(UserFRSConfirmRpcRequest_FieldNumber) {
  UserFRSConfirmRpcRequest_FieldNumber_AccessToken = 1,
  UserFRSConfirmRpcRequest_FieldNumber_RelationUserName = 11,
  UserFRSConfirmRpcRequest_FieldNumber_Action = 12,
};

/**
 * 请求方填写
 **/
@interface UserFRSConfirmRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** true; 被建立关系的用户名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *relationUserName;

/** true; 进行关系确认； 2，同意；3 拒绝  (被对方拒绝的关系可以再次编辑和申请) */
@property(nonatomic, readwrite) uint32_t action;

@end

#pragma mark - UserFRSConfirmRpcResponse

/**
 * 返回方填写
 **/
@interface UserFRSConfirmRpcResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
