// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAttrGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserAttrGetUserAttr;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserAttrGetUserAttrGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserAttrGetUserAttrGetRoot : GPBRootObject
@end

#pragma mark - UserAttrGetUserAttr

typedef GPB_ENUM(UserAttrGetUserAttr_FieldNumber) {
  UserAttrGetUserAttr_FieldNumber_UserId = 1,
  UserAttrGetUserAttr_FieldNumber_UserName = 2,
  UserAttrGetUserAttr_FieldNumber_LikeName = 4,
  UserAttrGetUserAttr_FieldNumber_Sign = 5,
  UserAttrGetUserAttr_FieldNumber_PicFileid = 6,
  UserAttrGetUserAttr_FieldNumber_BirthYear = 11,
  UserAttrGetUserAttr_FieldNumber_BirthMonth = 12,
  UserAttrGetUserAttr_FieldNumber_BirthDay = 13,
  UserAttrGetUserAttr_FieldNumber_Sex = 14,
  UserAttrGetUserAttr_FieldNumber_CompanyCode = 15,
  UserAttrGetUserAttr_FieldNumber_Height = 21,
  UserAttrGetUserAttr_FieldNumber_Weight = 22,
  UserAttrGetUserAttr_FieldNumber_TargetStep = 23,
  UserAttrGetUserAttr_FieldNumber_CardId = 24,
  UserAttrGetUserAttr_FieldNumber_Longitude = 31,
  UserAttrGetUserAttr_FieldNumber_Latitude = 32,
  UserAttrGetUserAttr_FieldNumber_SiteName = 33,
};

@interface UserAttrGetUserAttr : GPBMessage

/** true; 用户ID */
@property(nonatomic, readwrite) uint32_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *likeName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

/** 头像图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *picFileid;

/** true; 生日年份,例如：2004年该值为2004. */
@property(nonatomic, readwrite) int32_t birthYear;

/** true;生日月份，例如: 5月该值为5 */
@property(nonatomic, readwrite) int32_t birthMonth;

/** true;生日日期，例如： 20日该值为20 */
@property(nonatomic, readwrite) int32_t birthDay;

/** true;性别（1,男；2，女；3，中性） */
@property(nonatomic, readwrite) int32_t sex;

/** false; 公司代码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite) int32_t weight;

@property(nonatomic, readwrite) int32_t targetStep;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cardId;

/** true; 经度 */
@property(nonatomic, readwrite) int32_t longitude;

/** true; 纬度 */
@property(nonatomic, readwrite) int32_t latitude;

/** true; 小区名称或者位置名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *siteName;

@end

#pragma mark - UserAttrGetRpcRequest

typedef GPB_ENUM(UserAttrGetRpcRequest_FieldNumber) {
  UserAttrGetRpcRequest_FieldNumber_AccessToken = 1,
  UserAttrGetRpcRequest_FieldNumber_UserIdsArray = 11,
};

/**
 * 请求方填写
 **/
@interface UserAttrGetRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** true; 用户名集合(如果为空，则表示获取自己的) */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *userIdsArray;
/** The number of items in @c userIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdsArray_Count;

@end

#pragma mark - UserAttrGetRpcResponse

typedef GPB_ENUM(UserAttrGetRpcResponse_FieldNumber) {
  UserAttrGetRpcResponse_FieldNumber_AttrsArray = 11,
};

/**
 * 返回方填写
 **/
@interface UserAttrGetRpcResponse : GPBMessage

/** true; 用户基本信息数组 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserAttrGetUserAttr*> *attrsArray;
/** The number of items in @c attrsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attrsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
