// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserDeviceInfoGet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserDeviceInfoGetUserDeviceInfoGetRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserDeviceInfoGetUserDeviceInfoGetRoot : GPBRootObject
@end

#pragma mark - UserDeviceInfoGetRpcRequest

typedef GPB_ENUM(UserDeviceInfoGetRpcRequest_FieldNumber) {
  UserDeviceInfoGetRpcRequest_FieldNumber_AccessToken = 1,
  UserDeviceInfoGetRpcRequest_FieldNumber_DeviceId = 11,
  UserDeviceInfoGetRpcRequest_FieldNumber_SubDeviceId = 12,
};

/**
 * 请求方填写
 **/
@interface UserDeviceInfoGetRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@end

#pragma mark - UserDeviceInfoGetRpcResponse

typedef GPB_ENUM(UserDeviceInfoGetRpcResponse_FieldNumber) {
  UserDeviceInfoGetRpcResponse_FieldNumber_DeviceId = 1,
  UserDeviceInfoGetRpcResponse_FieldNumber_SubDeviceId = 2,
  UserDeviceInfoGetRpcResponse_FieldNumber_SwVer = 3,
  UserDeviceInfoGetRpcResponse_FieldNumber_HwVer = 4,
  UserDeviceInfoGetRpcResponse_FieldNumber_ProdtCodeArray = 5,
  UserDeviceInfoGetRpcResponse_FieldNumber_NbiCodeArray = 6,
  UserDeviceInfoGetRpcResponse_FieldNumber_ProductCode = 7,
  UserDeviceInfoGetRpcResponse_FieldNumber_ProductName = 8,
  UserDeviceInfoGetRpcResponse_FieldNumber_CompanyCode = 9,
  UserDeviceInfoGetRpcResponse_FieldNumber_Pic1Fileid = 10,
  UserDeviceInfoGetRpcResponse_FieldNumber_Pic2Fileid = 11,
  UserDeviceInfoGetRpcResponse_FieldNumber_Pic3Fileid = 12,
  UserDeviceInfoGetRpcResponse_FieldNumber_OwnerId = 13,
  UserDeviceInfoGetRpcResponse_FieldNumber_DeviceName = 14,
  UserDeviceInfoGetRpcResponse_FieldNumber_AreaName = 15,
  UserDeviceInfoGetRpcResponse_FieldNumber_HouseName = 16,
  UserDeviceInfoGetRpcResponse_FieldNumber_OwnerNick = 17,
  UserDeviceInfoGetRpcResponse_FieldNumber_HouseGuid = 18,
};

/**
 * 返回方填写
 **/
@interface UserDeviceInfoGetRpcResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *swVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwVer;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *prodtCodeArray;
/** The number of items in @c prodtCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger prodtCodeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *nbiCodeArray;
/** The number of items in @c nbiCodeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nbiCodeArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *companyCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic1Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic2Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic3Fileid;

@property(nonatomic, readwrite) uint32_t ownerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *areaName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ownerNick;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseGuid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
