// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserRefreshToken.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRefreshTokenUserRefreshTokenRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserRefreshTokenUserRefreshTokenRoot : GPBRootObject
@end

#pragma mark - UserRefreshTokenRpcRequest

typedef GPB_ENUM(UserRefreshTokenRpcRequest_FieldNumber) {
  UserRefreshTokenRpcRequest_FieldNumber_ClientId = 1,
  UserRefreshTokenRpcRequest_FieldNumber_ReqTime = 2,
  UserRefreshTokenRpcRequest_FieldNumber_SignKey = 3,
  UserRefreshTokenRpcRequest_FieldNumber_UserName = 11,
  UserRefreshTokenRpcRequest_FieldNumber_RefreshToken = 12,
};

/**
 * 请求方填写
 **/
@interface UserRefreshTokenRpcRequest : GPBMessage

/** true;平台申请 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

/** true;单位秒,请求时间戳，在该时间开始的15分钟内该请求有效，放置数据重放攻击. */
@property(nonatomic, readwrite) int64_t reqTime;

/** true;签名字串,计算方法： md5(req_time + client_srcret) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signKey;

/** true; 用户手机号码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

/** true;refresh_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *refreshToken;

@end

#pragma mark - UserRefreshTokenRpcResponse

typedef GPB_ENUM(UserRefreshTokenRpcResponse_FieldNumber) {
  UserRefreshTokenRpcResponse_FieldNumber_UserId = 1,
  UserRefreshTokenRpcResponse_FieldNumber_AccessToken = 2,
  UserRefreshTokenRpcResponse_FieldNumber_RefreshToken = 3,
  UserRefreshTokenRpcResponse_FieldNumber_ExpiredTime = 4,
};

/**
 * 返回方填写
 **/
@interface UserRefreshTokenRpcResponse : GPBMessage

/** true;用户ID */
@property(nonatomic, readwrite) uint32_t userId;

/** true;访问token，后续其它接口需要使用. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/** true;刷新token，在access_token到期之前可以通过该token刷新access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *refreshToken;

/** true;access_token 超时时间。当前时间加上该时间,是失效时间. */
@property(nonatomic, readwrite) int64_t expiredTime;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
