// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserDeviceListAdv.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserDeviceListAdvDeviceInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserDeviceListAdvUserDeviceListAdvRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserDeviceListAdvUserDeviceListAdvRoot : GPBRootObject
@end

#pragma mark - UserDeviceListAdvDeviceInfo

typedef GPB_ENUM(UserDeviceListAdvDeviceInfo_FieldNumber) {
  UserDeviceListAdvDeviceInfo_FieldNumber_DeviceId = 1,
  UserDeviceListAdvDeviceInfo_FieldNumber_SubDeviceId = 2,
  UserDeviceListAdvDeviceInfo_FieldNumber_DeviceName = 3,
  UserDeviceListAdvDeviceInfo_FieldNumber_Online = 6,
  UserDeviceListAdvDeviceInfo_FieldNumber_TimeStamp = 7,
  UserDeviceListAdvDeviceInfo_FieldNumber_ProdtTypeArray = 8,
  UserDeviceListAdvDeviceInfo_FieldNumber_Conf = 10,
  UserDeviceListAdvDeviceInfo_FieldNumber_OwnerId = 11,
  UserDeviceListAdvDeviceInfo_FieldNumber_Pic1Fileid = 12,
  UserDeviceListAdvDeviceInfo_FieldNumber_Pic2Fileid = 13,
  UserDeviceListAdvDeviceInfo_FieldNumber_Pic3Fileid = 14,
  UserDeviceListAdvDeviceInfo_FieldNumber_AreaName = 15,
  UserDeviceListAdvDeviceInfo_FieldNumber_HouseName = 16,
};

@interface UserDeviceListAdvDeviceInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subDeviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

/** 1: offline ; 2: online */
@property(nonatomic, readwrite) uint32_t online;

/** 最后更新时间 */
@property(nonatomic, readwrite) int64_t timeStamp;

/** [当sub_device_id 为空时才设置该值]设备类别 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *prodtTypeArray;
/** The number of items in @c prodtTypeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger prodtTypeArray_Count;

/**
 * 设备配置信息,每个 prodt_code对应的的配置信息参见: `device_confi.md`
 * add: 2018-0327 wbw
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *conf;

/** 设备属于谁 */
@property(nonatomic, readwrite) uint32_t ownerId;

/** 设备图片(3个尺寸,APP端可缓存) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pic1Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic2Fileid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pic3Fileid;

/** 设备位置信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *areaName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *houseName;

@end

#pragma mark - UserDeviceListAdvRpcRequest

typedef GPB_ENUM(UserDeviceListAdvRpcRequest_FieldNumber) {
  UserDeviceListAdvRpcRequest_FieldNumber_AccessToken = 1,
  UserDeviceListAdvRpcRequest_FieldNumber_Page = 11,
  UserDeviceListAdvRpcRequest_FieldNumber_PageSize = 12,
  UserDeviceListAdvRpcRequest_FieldNumber_ProdtCode = 13,
  UserDeviceListAdvRpcRequest_FieldNumber_ListType = 14,
};

/**
 * 请求方填写
 **/
@interface UserDeviceListAdvRpcRequest : GPBMessage

/** true; access_token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

/**
 * 分页信息
 * page == 0 / page_size == 0 表示获取所有记录
 * true;第几页数据，数据是按照默认排序从 (page-1) * page_size 到 page * page_size 之间的数据
 **/
@property(nonatomic, readwrite) uint32_t page;

/** true; 每页多少条数据 */
@property(nonatomic, readwrite) uint32_t pageSize;

/** true; 分类获取设备(2018-02-28) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *prodtCode;

/** true; 1, 只获取属于我的的设备; 2, 只获取别人分享给我的设备； 3，前面两种 */
@property(nonatomic, readwrite) uint32_t listType;

@end

#pragma mark - UserDeviceListAdvRpcResponse

typedef GPB_ENUM(UserDeviceListAdvRpcResponse_FieldNumber) {
  UserDeviceListAdvRpcResponse_FieldNumber_Total = 1,
  UserDeviceListAdvRpcResponse_FieldNumber_DevsArray = 2,
};

/**
 * 返回方填写
 **/
@interface UserDeviceListAdvRpcResponse : GPBMessage

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserDeviceListAdvDeviceInfo*> *devsArray;
/** The number of items in @c devsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger devsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
